"use client";

import { useState } from "react";
import { ModalFrame } from "@/components/ui/ModalFrame";
import type { Home, HomeMortgageDeal } from "@/components/mortgage/MortgagePlannerClient";

type Mode = "url" | "image" | "manual" | null;
type Quote = { lender_name: string; product_name: string; rate_percent: number; rate_type: string; ltv_max_percent: number | null; initial_term_months: number | null; fee_amount: number | null };
const EMPTY: Quote = { lender_name: "", product_name: "", rate_percent: 0, rate_type: "fixed", ltv_max_percent: null, initial_term_months: 24, fee_amount: 0 };

export function MortgageQuoteIntake({ currentHome, currentDeal: _currentDeal }: { currentHome?: Home; currentDeal?: HomeMortgageDeal }) {
  const [mode, setMode] = useState<Mode>(null), [url, setUrl] = useState(""), [busy, setBusy] = useState(false), [message, setMessage] = useState<string | null>(null), [quote, setQuote] = useState<Quote>(EMPTY), [fileName, setFileName] = useState("");
  const merge = (p: any) => setQuote({ lender_name: String(p?.lender_name || ""), product_name: String(p?.product_name || ""), rate_percent: Number(p?.rate_percent || 0), rate_type: String(p?.rate_type || "fixed"), ltv_max_percent: p?.ltv_max_percent == null ? null : Number(p.ltv_max_percent), initial_term_months: p?.initial_term_months == null ? null : Number(p.initial_term_months), fee_amount: p?.fee_amount == null ? null : Number(p.fee_amount) });
  async function fromUrl() { if (!url.trim() || !currentHome) return; setBusy(true); setMessage(null); try { const r = await fetch("/api/house/mortgage/import-product-url", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ sourceUrl: url.trim(), homeId: currentHome.id }) }); const d = await r.json(); if (!r.ok) throw new Error(d?.error || "Could not read quote"); merge(d.product); setMessage("Quote extracted. Check the fields before relying on the comparison."); } catch(e) { setMessage(e instanceof Error ? e.message : "Could not read quote"); } finally { setBusy(false); } }
  async function fromImage(file?: File) { if (!file) return; setFileName(file.name); setBusy(true); setMessage(null); try { const f = new FormData(); f.append("image", file); const r = await fetch("/api/house/mortgage/import-product-image", { method: "POST", body: f }); const d = await r.json(); if (!r.ok) throw new Error(d?.error || "Could not read image"); merge(d.product); setMessage("Image read. Check every extracted field before using it."); } catch(e) { setMessage(e instanceof Error ? e.message : "Could not read image"); } finally { setBusy(false); } }
  const fields = <div className="grid gap-3 sm:grid-cols-2">{[
    ["Lender", "lender_name", "text"], ["Product name", "product_name", "text"], ["Rate %", "rate_percent", "number"], ["Initial period months", "initial_term_months", "number"], ["Product fee £", "fee_amount", "number"], ["Max LTV %", "ltv_max_percent", "number"],
  ].map(([label,key,type]) => <label key={key} className="block"><span className="text-xs font-bold text-slate-600">{label}</span><input type={type} step={type === "number" ? "0.01" : undefined} value={(quote as any)[key] ?? ""} onChange={e => setQuote({ ...quote, [key]: type === "number" ? (e.target.value ? Number(e.target.value) : null) : e.target.value } as Quote)} className="mt-1 w-full rounded-xl border border-slate-200 px-3 py-2.5 text-sm outline-none focus:ring-2 focus:ring-violet-300"/></label>)}</div>;
  return <><section className="rounded-2xl border border-dashed border-violet-300 bg-violet-50/40 p-5"><div className="flex flex-col gap-4 lg:flex-row lg:items-center lg:justify-between"><div><p className="font-bold text-violet-800">Input a lender quote</p><p className="mt-1 max-w-2xl text-xs leading-5 text-slate-500">Use a product URL, screenshot/image or enter the quote manually. Imported fields remain reviewable rather than being silently trusted.</p></div><div className="grid grid-cols-3 gap-2"><button onClick={() => {setMode("url");setMessage(null)}} className="rounded-xl border border-violet-200 bg-white px-4 py-3 text-xs font-bold text-violet-700">🔗 URL</button><button onClick={() => {setMode("image");setMessage(null)}} className="rounded-xl border border-violet-200 bg-white px-4 py-3 text-xs font-bold text-violet-700">🖼 Image</button><button onClick={() => {setQuote(EMPTY);setMode("manual");setMessage(null)}} className="rounded-xl border border-violet-200 bg-white px-4 py-3 text-xs font-bold text-violet-700">✎ Manual</button></div></div></section>
  {mode ? <ModalFrame title={mode === "url" ? "Import lender quote from URL" : mode === "image" ? "Import lender quote from image" : "Enter lender quote manually"} onClose={() => setMode(null)}><div className="space-y-5">
    {mode === "url" ? <div><p className="text-sm text-slate-600">Paste the lender's specific product page. LOOP will only keep fields it can evidence.</p><div className="mt-3 flex gap-2"><input value={url} onChange={e=>setUrl(e.target.value)} placeholder="https://..." className="min-w-0 flex-1 rounded-xl border border-slate-200 px-4 py-3 text-sm"/><button onClick={fromUrl} disabled={busy || !url.trim()} className="rounded-xl bg-slate-950 px-5 py-3 text-sm font-bold text-white disabled:opacity-40">{busy ? "Checking…" : "Read quote"}</button></div></div> : null}
    {mode === "image" ? <label className="flex cursor-pointer flex-col items-center rounded-2xl border-2 border-dashed border-slate-200 bg-slate-50 p-8 text-center"><span className="text-2xl">🖼</span><span className="mt-2 text-sm font-bold">{fileName || "Choose screenshot or photo"}</span><span className="text-xs text-slate-400">PNG, JPG, WEBP · max 8MB</span><input type="file" accept="image/png,image/jpeg,image/webp" className="sr-only" onChange={e=>void fromImage(e.target.files?.[0])}/></label> : null}
    {message ? <p className="rounded-xl bg-slate-50 p-3 text-xs font-bold text-slate-600">{message}</p> : null}
    {(mode === "manual" || quote.rate_percent > 0) ? fields : null}
    {(mode === "manual" || quote.rate_percent > 0) ? <p className="text-[11px] leading-5 text-slate-400">This is an indicative quote input. Eligibility, fees, ERCs and lender affordability still need checking.</p> : null}
  </div></ModalFrame> : null}</>;
}
