/**
 * ============================================================================
 * FILE: provider-fund-catalogue.ts
 * DESCRIPTION: Master bootstrap catalogue of UK pension and retail investment funds.
 *              Acts as the source of truth for platform mappings, fee models, and DB hydration.
 *              Keep prices/fees source-backed and dated. Daily prices should be 
 *              refreshed into the DB, not treated as permanent constants.
 * ============================================================================
 */

export interface ProviderFund {
  readonly id: string;
  readonly provider_id: string;
  readonly fund_name: string;
  readonly fund_code: string | null;           // ISIN, SEDOL, or Ticker if available
  readonly group_label: string;
  readonly annual_fund_fee_percent: number | null;
  readonly unit_price: number | null;
  readonly unit_price_quote_unit: 'gbx' | 'gbp' | 'usd' | 'eur';
  readonly source_url: string;
  readonly confidence: number;                 // Data confidence score (0 - 100)
  readonly notes?: string;
}

// Provider fund catalogue bootstrap data.
export const PROVIDER_FUND_CATALOGUE: ReadonlyArray<ProviderFund> = [
  // --- LEGAL & GENERAL (L&G) ---
  {
    "id": "legal-general-landg-pmc-hsbc-islamic-global-equity-index-fund-3",
    "provider_id": "legal-general",
    "fund_name": "L&G PMC HSBC Islamic Global Equity Index Fund 3",
    "fund_code": "GB00BJXRF945",
    "group_label": "Global equity",
    "annual_fund_fee_percent": 0.2,
    "unit_price": 47.9037,
    "unit_price_quote_unit": "gbx",
    "source_url": "https://fundcentres.landg.com/en/uk/private-investors/fund-centre/",
    "confidence": 98,
    "notes": "User/provider screen value supplied 2026-06-15: 4,790.37p and 0.2% fund management charge. Check workplace plan/platform charge separately."
  },
  {
    "id": "legal-general-landg-pmc-lazard-emerging-markets-3",
    "provider_id": "legal-general",
    "fund_name": "L&G PMC Lazard Emerging Markets 3",
    "fund_code": null,
    "group_label": "Emerging markets",
    "annual_fund_fee_percent": 0.94,
    "unit_price": 23.4455,
    "unit_price_quote_unit": "gbx",
    "source_url": "https://fundcentres.landg.com/en/uk/private-investors/fund-centre/",
    "confidence": 98,
    "notes": "User/provider screen value supplied 2026-06-15: 2,344.55p and 0.94% fund management charge. Check workplace plan/platform charge separately."
  },
  {
    "id": "legal-general-landg-pmc-ct-responsible-global-equity-fund-3",
    "provider_id": "legal-general",
    "fund_name": "L&G PMC CT Responsible Global Equity Fund 3",
    "fund_code": null,
    "group_label": "Responsible global equity",
    "annual_fund_fee_percent": 0.74,
    "unit_price": 19.6497,
    "unit_price_quote_unit": "gbx",
    "source_url": "https://fundcentres.landg.com/en/uk/private-investors/fund-centre/",
    "confidence": 98,
    "notes": "User/provider screen value supplied 2026-06-15: 1,964.97p and 0.74% fund management charge. Check workplace plan/platform charge separately."
  },
  {
    "id": "legal-general-landg-pmc-multi-asset-3",
    "provider_id": "legal-general",
    "fund_name": "L&G PMC Multi-Asset 3",
    "fund_code": null,
    "group_label": "Multi-asset",
    "annual_fund_fee_percent": 0.13,
    "unit_price": 2.6582,
    "unit_price_quote_unit": "gbx",
    "source_url": "https://fundcentres.landg.com/en/uk/private-investors/fund-centre/",
    "confidence": 98,
    "notes": "User/provider screen value supplied 2026-06-15: 265.82p and 0.13% fund management charge. Check workplace plan/platform charge separately."
  },
  {
    "id": "legal-general-landg-pmc-uk-equity-index-fund-3",
    "provider_id": "legal-general",
    "fund_name": "L&G PMC UK Equity Index Fund 3",
    "fund_code": null,
    "group_label": "UK equity",
    "annual_fund_fee_percent": null,
    "unit_price": null,
    "unit_price_quote_unit": "gbx",
    "source_url": "https://fundcentres.landg.com/en/uk/private-investors/fund-centre/",
    "confidence": 50,
    "notes": "Needs provider/source refresh before relying on fee/price."
  },
  {
    "id": "legal-general-landg-pmc-uk-equity-index-fund-5",
    "provider_id": "legal-general",
    "fund_name": "L&G PMC UK Equity Index Fund 5",
    "fund_code": null,
    "group_label": "UK equity",
    "annual_fund_fee_percent": null,
    "unit_price": null,
    "unit_price_quote_unit": "gbx",
    "source_url": "https://fundcentres.landg.com/en/uk/private-investors/fund-centre/",
    "confidence": 50,
    "notes": "Needs provider/source refresh before relying on fee/price."
  },
  {
    "id": "legal-general-landg-pmc-uk-smaller-companies-fund-3",
    "provider_id": "legal-general",
    "fund_name": "L&G PMC UK Smaller Companies Fund 3",
    "fund_code": null,
    "group_label": "UK smaller companies",
    "annual_fund_fee_percent": null,
    "unit_price": null,
    "unit_price_quote_unit": "gbx",
    "source_url": "https://fundcentres.landg.com/en/uk/private-investors/fund-centre/",
    "confidence": 50,
    "notes": "Needs provider/source refresh before relying on fee/price."
  },
  {
    "id": "legal-general-landg-pmc-world-ex-uk-equity-index-fund-3",
    "provider_id": "legal-general",
    "fund_name": "L&G PMC World ex-UK Equity Index Fund 3",
    "fund_code": null,
    "group_label": "Global equity",
    "annual_fund_fee_percent": null,
    "unit_price": null,
    "unit_price_quote_unit": "gbx",
    "source_url": "https://fundcentres.landg.com/en/uk/private-investors/fund-centre/",
    "confidence": 50,
    "notes": "Needs provider/source refresh before relying on fee/price."
  },
  {
    "id": "legal-general-landg-pmc-world-ex-uk-equity-index-fund-5",
    "provider_id": "legal-general",
    "fund_name": "L&G PMC World ex-UK Equity Index Fund 5",
    "fund_code": null,
    "group_label": "Global equity",
    "annual_fund_fee_percent": null,
    "unit_price": null,
    "unit_price_quote_unit": "gbx",
    "source_url": "https://fundcentres.landg.com/en/uk/private-investors/fund-centre/",
    "confidence": 50,
    "notes": "Needs provider/source refresh before relying on fee/price."
  },
  {
    "id": "legal-general-landg-pmc-north-america-equity-index-fund-3",
    "provider_id": "legal-general",
    "fund_name": "L&G PMC North America Equity Index Fund 3",
    "fund_code": null,
    "group_label": "North America equity",
    "annual_fund_fee_percent": null,
    "unit_price": null,
    "unit_price_quote_unit": "gbx",
    "source_url": "https://fundcentres.landg.com/en/uk/private-investors/fund-centre/",
    "confidence": 50,
    "notes": "Needs provider/source refresh before relying on fee/price."
  },
  {
    "id": "legal-general-landg-pmc-europe-ex-uk-equity-index-fund-3",
    "provider_id": "legal-general",
    "fund_name": "L&G PMC Europe ex-UK Equity Index Fund 3",
    "fund_code": null,
    "group_label": "Europe equity",
    "annual_fund_fee_percent": null,
    "unit_price": null,
    "unit_price_quote_unit": "gbx",
    "source_url": "https://fundcentres.landg.com/en/uk/private-investors/fund-centre/",
    "confidence": 50,
    "notes": "Needs provider/source refresh before relying on fee/price."
  },
  {
    "id": "legal-general-landg-pmc-japan-equity-index-fund-3",
    "provider_id": "legal-general",
    "fund_name": "L&G PMC Japan Equity Index Fund 3",
    "fund_code": null,
    "group_label": "Japan equity",
    "annual_fund_fee_percent": null,
    "unit_price": null,
    "unit_price_quote_unit": "gbx",
    "source_url": "https://fundcentres.landg.com/en/uk/private-investors/fund-centre/",
    "confidence": 50,
    "notes": "Needs provider/source refresh before relying on fee/price."
  },
  {
    "id": "legal-general-landg-pmc-asia-pacific-ex-japan-equity-index-fund-3",
    "provider_id": "legal-general",
    "fund_name": "L&G PMC Asia Pacific ex-Japan Equity Index Fund 3",
    "fund_code": null,
    "group_label": "Asia Pacific equity",
    "annual_fund_fee_percent": null,
    "unit_price": null,
    "unit_price_quote_unit": "gbx",
    "source_url": "https://fundcentres.landg.com/en/uk/private-investors/fund-centre/",
    "confidence": 50,
    "notes": "Needs provider/source refresh before relying on fee/price."
  },
  {
    "id": "legal-general-landg-pmc-emerging-markets-equity-index-fund-3",
    "provider_id": "legal-general",
    "fund_name": "L&G PMC Emerging Markets Equity Index Fund 3",
    "fund_code": null,
    "group_label": "Emerging markets",
    "annual_fund_fee_percent": null,
    "unit_price": null,
    "unit_price_quote_unit": "gbx",
    "source_url": "https://fundcentres.landg.com/en/uk/private-investors/fund-centre/",
    "confidence": 50,
    "notes": "Needs provider/source refresh before relying on fee/price."
  },
  {
    "id": "legal-general-landg-pmc-global-equity-fixed-weights-50-50-index-fund-3",
    "provider_id": "legal-general",
    "fund_name": "L&G PMC Global Equity Fixed Weights 50:50 Index Fund 3",
    "fund_code": null,
    "group_label": "Global equity",
    "annual_fund_fee_percent": null,
    "unit_price": null,
    "unit_price_quote_unit": "gbx",
    "source_url": "https://fundcentres.landg.com/en/uk/private-investors/fund-centre/",
    "confidence": 50,
    "notes": "Needs provider/source refresh before relying on fee/price."
  },
  {
    "id": "legal-general-landg-pmc-ethical-global-equity-index-fund-3",
    "provider_id": "legal-general",
    "fund_name": "L&G PMC Ethical Global Equity Index Fund 3",
    "fund_code": null,
    "group_label": "Ethical global equity",
    "annual_fund_fee_percent": null,
    "unit_price": null,
    "unit_price_quote_unit": "gbx",
    "source_url": "https://fundcentres.landg.com/en/uk/private-investors/fund-centre/",
    "confidence": 50,
    "notes": "Needs provider/source refresh before relying on fee/price."
  },
  {
    "id": "legal-general-landg-pmc-future-world-global-equity-index-fund-3",
    "provider_id": "legal-general",
    "fund_name": "L&G PMC Future World Global Equity Index Fund 3",
    "fund_code": null,
    "group_label": "Future World",
    "annual_fund_fee_percent": null,
    "unit_price": null,
    "unit_price_quote_unit": "gbx",
    "source_url": "https://fundcentres.landg.com/en/uk/private-investors/fund-centre/",
    "confidence": 50,
    "notes": "Needs provider/source refresh before relying on fee/price."
  },
  {
    "id": "legal-general-landg-pmc-future-world-annuity-aware-fund-3",
    "provider_id": "legal-general",
    "fund_name": "L&G PMC Future World Annuity Aware Fund 3",
    "fund_code": null,
    "group_label": "Lifestyle/annuity aware",
    "annual_fund_fee_percent": null,
    "unit_price": null,
    "unit_price_quote_unit": "gbx",
    "source_url": "https://fundcentres.landg.com/en/uk/private-investors/fund-centre/",
    "confidence": 50,
    "notes": "Needs provider/source refresh before relying on fee/price."
  },
  {
    "id": "legal-general-landg-pmc-future-world-multi-asset-fund-3",
    "provider_id": "legal-general",
    "fund_name": "L&G PMC Future World Multi-Asset Fund 3",
    "fund_code": null,
    "group_label": "Future World multi-asset",
    "annual_fund_fee_percent": null,
    "unit_price": null,
    "unit_price_quote_unit": "gbx",
    "source_url": "https://fundcentres.landg.com/en/uk/private-investors/fund-centre/",
    "confidence": 50,
    "notes": "Needs provider/source refresh before relying on fee/price."
  },
  {
    "id": "legal-general-landg-pmc-diversified-fund-3",
    "provider_id": "legal-general",
    "fund_name": "L&G PMC Diversified Fund 3",
    "fund_code": null,
    "group_label": "Multi-asset",
    "annual_fund_fee_percent": null,
    "unit_price": null,
    "unit_price_quote_unit": "gbx",
    "source_url": "https://fundcentres.landg.com/en/uk/private-investors/fund-centre/",
    "confidence": 50,
    "notes": "Needs provider/source refresh before relying on fee/price."
  },
  {
    "id": "legal-general-landg-pmc-pre-retirement-fund-3",
    "provider_id": "legal-general",
    "fund_name": "L&G PMC Pre-Retirement Fund 3",
    "fund_code": null,
    "group_label": "Pre-retirement",
    "annual_fund_fee_percent": null,
    "unit_price": null,
    "unit_price_quote_unit": "gbx",
    "source_url": "https://fundcentres.landg.com/en/uk/private-investors/fund-centre/",
    "confidence": 50,
    "notes": "Needs provider/source refresh before relying on fee/price."
  },
  {
    "id": "legal-general-landg-pmc-cash-fund-3",
    "provider_id": "legal-general",
    "fund_name": "L&G PMC Cash Fund 3",
    "fund_code": "GB00B0CNHB64", // Enriched: Institutional ISIN for L&G Cash Trust
    "group_label": "Cash",
    "annual_fund_fee_percent": 0.15,
    "unit_price": null,
    "unit_price_quote_unit": "gbx",
    "source_url": "https://fundcentres.landg.com/en/uk/private-investors/fund-centre/",
    "confidence": 50,
    "notes": "Needs provider/source refresh before relying on fee/price."
  },
  {
    "id": "legal-general-landg-pmc-over-5-year-index-linked-gilts-index-fund-3",
    "provider_id": "legal-general",
    "fund_name": "L&G PMC Over 5 Year Index-Linked Gilts Index Fund 3",
    "fund_code": null,
    "group_label": "Index-linked gilts",
    "annual_fund_fee_percent": null,
    "unit_price": null,
    "unit_price_quote_unit": "gbx",
    "source_url": "https://fundcentres.landg.com/en/uk/private-investors/fund-centre/",
    "confidence": 50,
    "notes": "Needs provider/source refresh before relying on fee/price."
  },
  {
    "id": "legal-general-landg-pmc-over-15-year-gilts-index-fund-3",
    "provider_id": "legal-general",
    "fund_name": "L&G PMC Over 15 Year Gilts Index Fund 3",
    "fund_code": null,
    "group_label": "Gilts",
    "annual_fund_fee_percent": null,
    "unit_price": null,
    "unit_price_quote_unit": "gbx",
    "source_url": "https://fundcentres.landg.com/en/uk/private-investors/fund-centre/",
    "confidence": 50,
    "notes": "Needs provider/source refresh before relying on fee/price."
  },
  {
    "id": "legal-general-landg-pmc-corporate-bond-all-stocks-index-fund-3",
    "provider_id": "legal-general",
    "fund_name": "L&G PMC Corporate Bond All Stocks Index Fund 3",
    "fund_code": null,
    "group_label": "Corporate bonds",
    "annual_fund_fee_percent": null,
    "unit_price": null,
    "unit_price_quote_unit": "gbx",
    "source_url": "https://fundcentres.landg.com/en/uk/private-investors/fund-centre/",
    "confidence": 50,
    "notes": "Needs provider/source refresh before relying on fee/price."
  },
  {
    "id": "legal-general-landg-pmc-aaa-aa-a-corporate-bond-all-stocks-index-fund-3",
    "provider_id": "legal-general",
    "fund_name": "L&G PMC AAA-AA-A Corporate Bond All Stocks Index Fund 3",
    "fund_code": null,
    "group_label": "Corporate bonds",
    "annual_fund_fee_percent": null,
    "unit_price": null,
    "unit_price_quote_unit": "gbx",
    "source_url": "https://fundcentres.landg.com/en/uk/private-investors/fund-centre/",
    "confidence": 50,
    "notes": "Needs provider/source refresh before relying on fee/price."
  },
  {
    "id": "legal-general-landg-pmc-property-fund-3",
    "provider_id": "legal-general",
    "fund_name": "L&G PMC Property Fund 3",
    "fund_code": null,
    "group_label": "Property",
    "annual_fund_fee_percent": null,
    "unit_price": null,
    "unit_price_quote_unit": "gbx",
    "source_url": "https://fundcentres.landg.com/en/uk/private-investors/fund-centre/",
    "confidence": 50,
    "notes": "Needs provider/source refresh before relying on fee/price."
  },
  {
    "id": "legal-general-landg-pmc-shariah-fund-3",
    "provider_id": "legal-general",
    "fund_name": "L&G PMC Shariah Fund 3",
    "fund_code": null,
    "group_label": "Shariah",
    "annual_fund_fee_percent": null,
    "unit_price": null,
    "unit_price_quote_unit": "gbx",
    "source_url": "https://fundcentres.landg.com/en/uk/private-investors/fund-centre/",
    "confidence": 50,
    "notes": "Needs provider/source refresh before relying on fee/price."
  },
  {
    "id": "legal-general-landg-pmc-ct-american-fund-3",
    "provider_id": "legal-general",
    "fund_name": "L&G PMC CT American Fund 3",
    "fund_code": null,
    "group_label": "US equity",
    "annual_fund_fee_percent": null,
    "unit_price": null,
    "unit_price_quote_unit": "gbx",
    "source_url": "https://fundcentres.landg.com/en/uk/private-investors/fund-centre/",
    "confidence": 50,
    "notes": "Needs provider/source refresh before relying on fee/price."
  },
  {
    "id": "legal-general-landg-pmc-ct-european-fund-3",
    "provider_id": "legal-general",
    "fund_name": "L&G PMC CT European Fund 3",
    "fund_code": null,
    "group_label": "Europe equity",
    "annual_fund_fee_percent": null,
    "unit_price": null,
    "unit_price_quote_unit": "gbx",
    "source_url": "https://fundcentres.landg.com/en/uk/private-investors/fund-centre/",
    "confidence": 50,
    "notes": "Needs provider/source refresh before relying on fee/price."
  },
  {
    "id": "legal-general-landg-pmc-ct-asia-pacific-fund-3",
    "provider_id": "legal-general",
    "fund_name": "L&G PMC CT Asia Pacific Fund 3",
    "fund_code": null,
    "group_label": "Asia Pacific equity",
    "annual_fund_fee_percent": null,
    "unit_price": null,
    "unit_price_quote_unit": "gbx",
    "source_url": "https://fundcentres.landg.com/en/uk/private-investors/fund-centre/",
    "confidence": 50,
    "notes": "Needs provider/source refresh before relying on fee/price."
  },
  {
    "id": "legal-general-landg-pmc-baillie-gifford-developed-asia-pacific-fund-3",
    "provider_id": "legal-general",
    "fund_name": "L&G PMC Baillie Gifford Developed Asia Pacific Fund 3",
    "fund_code": null,
    "group_label": "Asia Pacific equity",
    "annual_fund_fee_percent": null,
    "unit_price": null,
    "unit_price_quote_unit": "gbx",
    "source_url": "https://fundcentres.landg.com/en/uk/private-investors/fund-centre/",
    "confidence": 50,
    "notes": "Needs provider/source refresh before relying on fee/price."
  },
  {
    "id": "legal-general-landg-pmc-baillie-gifford-positive-change-fund-3",
    "provider_id": "legal-general",
    "fund_name": "L&G PMC Baillie Gifford Positive Change Fund 3",
    "fund_code": null,
    "group_label": "Sustainable equity",
    "annual_fund_fee_percent": null,
    "unit_price": null,
    "unit_price_quote_unit": "gbx",
    "source_url": "https://fundcentres.landg.com/en/uk/private-investors/fund-centre/",
    "confidence": 50,
    "notes": "Needs provider/source refresh before relying on fee/price."
  },
  {
    "id": "legal-general-landg-pmc-baillie-gifford-long-term-global-growth-fund-3",
    "provider_id": "legal-general",
    "fund_name": "L&G PMC Baillie Gifford Long Term Global Growth Fund 3",
    "fund_code": null,
    "group_label": "Global equity",
    "annual_fund_fee_percent": null,
    "unit_price": null,
    "unit_price_quote_unit": "gbx",
    "source_url": "https://fundcentres.landg.com/en/uk/private-investors/fund-centre/",
    "confidence": 50,
    "notes": "Needs provider/source refresh before relying on fee/price."
  },
  {
    "id": "legal-general-landg-pmc-mfs-meridian-global-equity-fund-3",
    "provider_id": "legal-general",
    "fund_name": "L&G PMC MFS Meridian Global Equity Fund 3",
    "fund_code": null,
    "group_label": "Global equity",
    "annual_fund_fee_percent": null,
    "unit_price": null,
    "unit_price_quote_unit": "gbx",
    "source_url": "https://fundcentres.landg.com/en/uk/private-investors/fund-centre/",
    "confidence": 50,
    "notes": "Needs provider/source refresh before relying on fee/price."
  },
  {
    "id": "legal-general-landg-pmc-lgim-global-equity-market-weights-30-70-index-fund-3",
    "provider_id": "legal-general",
    "fund_name": "L&G PMC LGIM Global Equity Market Weights 30:70 Index Fund 3",
    "fund_code": null,
    "group_label": "Global equity",
    "annual_fund_fee_percent": null,
    "unit_price": null,
    "unit_price_quote_unit": "gbx",
    "source_url": "https://fundcentres.landg.com/en/uk/private-investors/fund-centre/",
    "confidence": 50,
    "notes": "Needs provider/source refresh before relying on fee/price."
  },
  {
    "id": "legal-general-landg-pmc-lgim-global-equity-market-weights-50-50-index-fund-3",
    "provider_id": "legal-general",
    "fund_name": "L&G PMC LGIM Global Equity Market Weights 50:50 Index Fund 3",
    "fund_code": null,
    "group_label": "Global equity",
    "annual_fund_fee_percent": null,
    "unit_price": null,
    "unit_price_quote_unit": "gbx",
    "source_url": "https://fundcentres.landg.com/en/uk/private-investors/fund-centre/",
    "confidence": 50,
    "notes": "Needs provider/source refresh before relying on fee/price."
  },
  {
    "id": "legal-general-landg-pmc-lgim-global-equity-market-weights-70-30-index-fund-3",
    "provider_id": "legal-general",
    "fund_name": "L&G PMC LGIM Global Equity Market Weights 70:30 Index Fund 3",
    "fund_code": null,
    "group_label": "Global equity",
    "annual_fund_fee_percent": null,
    "unit_price": null,
    "unit_price_quote_unit": "gbx",
    "source_url": "https://fundcentres.landg.com/en/uk/private-investors/fund-centre/",
    "confidence": 50,
    "notes": "Needs provider/source refresh before relying on fee/price."
  },
  {
    "id": "legal-general-landg-pmc-retirement-income-multi-asset-fund-3",
    "provider_id": "legal-general",
    "fund_name": "L&G PMC Retirement Income Multi-Asset Fund 3",
    "fund_code": null,
    "group_label": "Retirement income",
    "annual_fund_fee_percent": null,
    "unit_price": null,
    "unit_price_quote_unit": "gbx",
    "source_url": "https://fundcentres.landg.com/en/uk/private-investors/fund-centre/",
    "confidence": 50,
    "notes": "Needs provider/source refresh before relying on fee/price."
  },
  {
    "id": "legal-general-landg-pmc-target-date-fund-2030",
    "provider_id": "legal-general",
    "fund_name": "L&G PMC Target Date Fund 2030",
    "fund_code": null,
    "group_label": "Target date",
    "annual_fund_fee_percent": null,
    "unit_price": null,
    "unit_price_quote_unit": "gbx",
    "source_url": "https://fundcentres.landg.com/en/uk/private-investors/fund-centre/",
    "confidence": 50,
    "notes": "Needs provider/source refresh before relying on fee/price."
  },
  {
    "id": "legal-general-landg-pmc-target-date-fund-2035",
    "provider_id": "legal-general",
    "fund_name": "L&G PMC Target Date Fund 2035",
    "fund_code": null,
    "group_label": "Target date",
    "annual_fund_fee_percent": null,
    "unit_price": null,
    "unit_price_quote_unit": "gbx",
    "source_url": "https://fundcentres.landg.com/en/uk/private-investors/fund-centre/",
    "confidence": 50,
    "notes": "Needs provider/source refresh before relying on fee/price."
  },
  {
    "id": "legal-general-landg-pmc-target-date-fund-2040",
    "provider_id": "legal-general",
    "fund_name": "L&G PMC Target Date Fund 2040",
    "fund_code": null,
    "group_label": "Target date",
    "annual_fund_fee_percent": null,
    "unit_price": null,
    "unit_price_quote_unit": "gbx",
    "source_url": "https://fundcentres.landg.com/en/uk/private-investors/fund-centre/",
    "confidence": 50,
    "notes": "Needs provider/source refresh before relying on fee/price."
  },
  {
    "id": "legal-general-landg-pmc-target-date-fund-2045",
    "provider_id": "legal-general",
    "fund_name": "L&G PMC Target Date Fund 2045",
    "fund_code": null,
    "group_label": "Target date",
    "annual_fund_fee_percent": null,
    "unit_price": null,
    "unit_price_quote_unit": "gbx",
    "source_url": "https://fundcentres.landg.com/en/uk/private-investors/fund-centre/",
    "confidence": 50,
    "notes": "Needs provider/source refresh before relying on fee/price."
  },
  {
    "id": "legal-general-landg-pmc-target-date-fund-2050",
    "provider_id": "legal-general",
    "fund_name": "L&G PMC Target Date Fund 2050",
    "fund_code": null,
    "group_label": "Target date",
    "annual_fund_fee_percent": null,
    "unit_price": null,
    "unit_price_quote_unit": "gbx",
    "source_url": "https://fundcentres.landg.com/en/uk/private-investors/fund-centre/",
    "confidence": 50,
    "notes": "Needs provider/source refresh before relying on fee/price."
  },
  {
    "id": "legal-general-landg-pmc-target-date-fund-2055",
    "provider_id": "legal-general",
    "fund_name": "L&G PMC Target Date Fund 2055",
    "fund_code": null,
    "group_label": "Target date",
    "annual_fund_fee_percent": null,
    "unit_price": null,
    "unit_price_quote_unit": "gbx",
    "source_url": "https://fundcentres.landg.com/en/uk/private-investors/fund-centre/",
    "confidence": 50,
    "notes": "Needs provider/source refresh before relying on fee/price."
  },
  {
    "id": "legal-general-landg-pmc-target-date-fund-2060",
    "provider_id": "legal-general",
    "fund_name": "L&G PMC Target Date Fund 2060",
    "fund_code": null,
    "group_label": "Target date",
    "annual_fund_fee_percent": null,
    "unit_price": null,
    "unit_price_quote_unit": "gbx",
    "source_url": "https://fundcentres.landg.com/en/uk/private-investors/fund-centre/",
    "confidence": 50,
    "notes": "Needs provider/source refresh before relying on fee/price."
  },

  // --- VANGUARD ---
  {
    "id": "vanguard-vanguard-ftse-global-all-cap-index-fund-accumulation",
    "provider_id": "vanguard",
    "fund_name": "Vanguard FTSE Global All Cap Index Fund Accumulation",
    "fund_code": "GB00BD3RZ582",
    "group_label": "Global equity",
    "annual_fund_fee_percent": 0.23,
    "unit_price": null,
    "unit_price_quote_unit": "gbp",
    "source_url": "https://www.vanguardinvestor.co.uk/",
    "confidence": 60,
    "notes": "Common Vanguard UK fund/ETF glossary entry. Unit price/NAV should be refreshed from provider or quote source; platform fee is account-level."
  },
  {
    "id": "vanguard-vanguard-ftse-developed-world-ex-u-k-equity-index-fund-accumulation",
    "provider_id": "vanguard",
    "fund_name": "Vanguard FTSE Developed World ex-U.K. Equity Index Fund Accumulation",
    "fund_code": null,
    "group_label": "Developed world equity",
    "annual_fund_fee_percent": null,
    "unit_price": null,
    "unit_price_quote_unit": "gbp",
    "source_url": "https://www.vanguardinvestor.co.uk/",
    "confidence": 60,
    "notes": "Common Vanguard UK fund/ETF glossary entry. Unit price/NAV should be refreshed from provider or quote source; platform fee is account-level."
  },
  {
    "id": "vanguard-vanguard-ftse-u-k-all-share-index-unit-trust-accumulation",
    "provider_id": "vanguard",
    "fund_name": "Vanguard FTSE U.K. All Share Index Unit Trust Accumulation",
    "fund_code": null,
    "group_label": "UK equity",
    "annual_fund_fee_percent": null,
    "unit_price": null,
    "unit_price_quote_unit": "gbp",
    "source_url": "https://www.vanguardinvestor.co.uk/",
    "confidence": 60,
    "notes": "Common Vanguard UK fund/ETF glossary entry. Unit price/NAV should be refreshed from provider or quote source; platform fee is account-level."
  },
  {
    "id": "vanguard-vanguard-u-s-equity-index-fund-accumulation",
    "provider_id": "vanguard",
    "fund_name": "Vanguard U.S. Equity Index Fund Accumulation",
    "fund_code": null,
    "group_label": "US equity",
    "annual_fund_fee_percent": null,
    "unit_price": null,
    "unit_price_quote_unit": "gbp",
    "source_url": "https://www.vanguardinvestor.co.uk/",
    "confidence": 60,
    "notes": "Common Vanguard UK fund/ETF glossary entry. Unit price/NAV should be refreshed from provider or quote source; platform fee is account-level."
  },
  {
    "id": "vanguard-vanguard-emerging-markets-stock-index-fund-accumulation",
    "provider_id": "vanguard",
    "fund_name": "Vanguard Emerging Markets Stock Index Fund Accumulation",
    "fund_code": null,
    "group_label": "Emerging markets",
    "annual_fund_fee_percent": null,
    "unit_price": null,
    "unit_price_quote_unit": "gbp",
    "source_url": "https://www.vanguardinvestor.co.uk/",
    "confidence": 60,
    "notes": "Common Vanguard UK fund/ETF glossary entry. Unit price/NAV should be refreshed from provider or quote source; platform fee is account-level."
  },
  {
    "id": "vanguard-vanguard-global-small-cap-index-fund-accumulation",
    "provider_id": "vanguard",
    "fund_name": "Vanguard Global Small-Cap Index Fund Accumulation",
    "fund_code": null,
    "group_label": "Global small cap",
    "annual_fund_fee_percent": null,
    "unit_price": null,
    "unit_price_quote_unit": "gbp",
    "source_url": "https://www.vanguardinvestor.co.uk/",
    "confidence": 60,
    "notes": "Common Vanguard UK fund/ETF glossary entry. Unit price/NAV should be refreshed from provider or quote source; platform fee is account-level."
  },
  {
    "id": "vanguard-vanguard-lifestrategy-20-equity-fund-accumulation",
    "provider_id": "vanguard",
    "fund_name": "Vanguard LifeStrategy 20% Equity Fund Accumulation",
    "fund_code": null,
    "group_label": "LifeStrategy",
    "annual_fund_fee_percent": 0.22,
    "unit_price": null,
    "unit_price_quote_unit": "gbp",
    "source_url": "https://www.vanguardinvestor.co.uk/",
    "confidence": 60,
    "notes": "Common Vanguard UK fund/ETF glossary entry. Unit price/NAV should be refreshed from provider or quote source; platform fee is account-level."
  },
  {
    "id": "vanguard-vanguard-lifestrategy-40-equity-fund-accumulation",
    "provider_id": "vanguard",
    "fund_name": "Vanguard LifeStrategy 40% Equity Fund Accumulation",
    "fund_code": null,
    "group_label": "LifeStrategy",
    "annual_fund_fee_percent": 0.22,
    "unit_price": null,
    "unit_price_quote_unit": "gbp",
    "source_url": "https://www.vanguardinvestor.co.uk/",
    "confidence": 60,
    "notes": "Common Vanguard UK fund/ETF glossary entry. Unit price/NAV should be refreshed from provider or quote source; platform fee is account-level."
  },
  {
    "id": "vanguard-vanguard-lifestrategy-60-equity-fund-accumulation",
    "provider_id": "vanguard",
    "fund_name": "Vanguard LifeStrategy 60% Equity Fund Accumulation",
    "fund_code": null,
    "group_label": "LifeStrategy",
    "annual_fund_fee_percent": 0.22,
    "unit_price": null,
    "unit_price_quote_unit": "gbp",
    "source_url": "https://www.vanguardinvestor.co.uk/",
    "confidence": 60,
    "notes": "Common Vanguard UK fund/ETF glossary entry. Unit price/NAV should be refreshed from provider or quote source; platform fee is account-level."
  },
  {
    "id": "vanguard-vanguard-lifestrategy-80-equity-fund-accumulation",
    "provider_id": "vanguard",
    "fund_name": "Vanguard LifeStrategy 80% Equity Fund Accumulation",
    "fund_code": null,
    "group_label": "LifeStrategy",
    "annual_fund_fee_percent": 0.22,
    "unit_price": null,
    "unit_price_quote_unit": "gbp",
    "source_url": "https://www.vanguardinvestor.co.uk/",
    "confidence": 60,
    "notes": "Common Vanguard UK fund/ETF glossary entry. Unit price/NAV should be refreshed from provider or quote source; platform fee is account-level."
  },
  {
    "id": "vanguard-vanguard-lifestrategy-100-equity-fund-accumulation",
    "provider_id": "vanguard",
    "fund_name": "Vanguard LifeStrategy 100% Equity Fund Accumulation",
    "fund_code": null,
    "group_label": "LifeStrategy",
    "annual_fund_fee_percent": 0.22,
    "unit_price": null,
    "unit_price_quote_unit": "gbp",
    "source_url": "https://www.vanguardinvestor.co.uk/",
    "confidence": 60,
    "notes": "Common Vanguard UK fund/ETF glossary entry. Unit price/NAV should be refreshed from provider or quote source; platform fee is account-level."
  },
  {
    "id": "vanguard-vanguard-ftse-all-world-ucits-etf-accumulating",
    "provider_id": "vanguard",
    "fund_name": "Vanguard FTSE All-World UCITS ETF Accumulating",
    "fund_code": "VWRP",
    "group_label": "Global equity ETF",
    "annual_fund_fee_percent": 0.22,
    "unit_price": null,
    "unit_price_quote_unit": "gbp",
    "source_url": "https://www.vanguardinvestor.co.uk/",
    "confidence": 60,
    "notes": "Common Vanguard UK fund/ETF glossary entry. Unit price/NAV should be refreshed from provider or quote source; platform fee is account-level."
  },
  {
    "id": "vanguard-vanguard-ftse-all-world-ucits-etf-distributing",
    "provider_id": "vanguard",
    "fund_name": "Vanguard FTSE All-World UCITS ETF Distributing",
    "fund_code": "VWRL",
    "group_label": "Global equity ETF",
    "annual_fund_fee_percent": 0.22,
    "unit_price": null,
    "unit_price_quote_unit": "gbp",
    "source_url": "https://www.vanguardinvestor.co.uk/",
    "confidence": 60,
    "notes": "Common Vanguard UK fund/ETF glossary entry. Unit price/NAV should be refreshed from provider or quote source; platform fee is account-level."
  },
  {
    "id": "vanguard-vanguard-sandp-500-ucits-etf-accumulating",
    "provider_id": "vanguard",
    "fund_name": "Vanguard S&P 500 UCITS ETF Accumulating",
    "fund_code": "VUAG",
    "group_label": "US equity ETF",
    "annual_fund_fee_percent": 0.07,
    "unit_price": null,
    "unit_price_quote_unit": "gbp",
    "source_url": "https://www.vanguardinvestor.co.uk/",
    "confidence": 60,
    "notes": "Common Vanguard UK fund/ETF glossary entry. Unit price/NAV should be refreshed from provider or quote source; platform fee is account-level."
  },
  {
    "id": "vanguard-vanguard-sandp-500-ucits-etf-distributing",
    "provider_id": "vanguard",
    "fund_name": "Vanguard S&P 500 UCITS ETF Distributing",
    "fund_code": "VUSA",
    "group_label": "US equity ETF",
    "annual_fund_fee_percent": 0.07,
    "unit_price": null,
    "unit_price_quote_unit": "gbp",
    "source_url": "https://www.vanguardinvestor.co.uk/",
    "confidence": 60,
    "notes": "Common Vanguard UK fund/ETF glossary entry. Unit price/NAV should be refreshed from provider or quote source; platform fee is account-level."
  },
  {
    "id": "vanguard-vanguard-ftse-100-ucits-etf-distributing",
    "provider_id": "vanguard",
    "fund_name": "Vanguard FTSE 100 UCITS ETF Distributing",
    "fund_code": "VUKE",
    "group_label": "UK equity ETF",
    "annual_fund_fee_percent": 0.09,
    "unit_price": null,
    "unit_price_quote_unit": "gbp",
    "source_url": "https://www.vanguardinvestor.co.uk/",
    "confidence": 60,
    "notes": "Common Vanguard UK fund/ETF glossary entry. Unit price/NAV should be refreshed from provider or quote source; platform fee is account-level."
  },
  {
    "id": "vanguard-vanguard-ftse-250-ucits-etf-distributing",
    "provider_id": "vanguard",
    "fund_name": "Vanguard FTSE 250 UCITS ETF Distributing",
    "fund_code": "VMID",
    "group_label": "UK mid-cap ETF",
    "annual_fund_fee_percent": 0.1,
    "unit_price": null,
    "unit_price_quote_unit": "gbp",
    "source_url": "https://www.vanguardinvestor.co.uk/",
    "confidence": 60,
    "notes": "Common Vanguard UK fund/ETF glossary entry. Unit price/NAV should be refreshed from provider or quote source; platform fee is account-level."
  },
  {
    "id": "vanguard-vanguard-ftse-developed-europe-ex-uk-ucits-etf",
    "provider_id": "vanguard",
    "fund_name": "Vanguard FTSE Developed Europe ex UK UCITS ETF",
    "fund_code": "VERX",
    "group_label": "Europe ETF",
    "annual_fund_fee_percent": null,
    "unit_price": null,
    "unit_price_quote_unit": "gbp",
    "source_url": "https://www.vanguardinvestor.co.uk/",
    "confidence": 60,
    "notes": "Common Vanguard UK fund/ETF glossary entry. Unit price/NAV should be refreshed from provider or quote source; platform fee is account-level."
  },
  {
    "id": "vanguard-vanguard-ftse-emerging-markets-ucits-etf",
    "provider_id": "vanguard",
    "fund_name": "Vanguard FTSE Emerging Markets UCITS ETF",
    "fund_code": "VFEM",
    "group_label": "Emerging markets ETF",
    "annual_fund_fee_percent": null,
    "unit_price": null,
    "unit_price_quote_unit": "gbp",
    "source_url": "https://www.vanguardinvestor.co.uk/",
    "confidence": 60,
    "notes": "Common Vanguard UK fund/ETF glossary entry. Unit price/NAV should be refreshed from provider or quote source; platform fee is account-level."
  },
  {
    "id": "vanguard-vanguard-global-aggregate-bond-ucits-etf",
    "provider_id": "vanguard",
    "fund_name": "Vanguard Global Aggregate Bond UCITS ETF",
    "fund_code": "VAGP",
    "group_label": "Global bonds ETF",
    "annual_fund_fee_percent": null,
    "unit_price": null,
    "unit_price_quote_unit": "gbp",
    "source_url": "https://www.vanguardinvestor.co.uk/",
    "confidence": 60,
    "notes": "Common Vanguard UK fund/ETF glossary entry. Unit price/NAV should be refreshed from provider or quote source; platform fee is account-level."
  },
  {
    "id": "vanguard-vanguard-u-k-government-bond-index-fund",
    "provider_id": "vanguard",
    "fund_name": "Vanguard U.K. Government Bond Index Fund",
    "fund_code": "GB00B1S75374",
    "group_label": "UK gilts",
    "annual_fund_fee_percent": null,
    "unit_price": null,
    "unit_price_quote_unit": "gbp",
    "source_url": "https://www.vanguardinvestor.co.uk/",
    "confidence": 60,
    "notes": "Common Vanguard UK fund/ETF glossary entry. Unit price/NAV should be refreshed from provider or quote source; platform fee is account-level."
  },
  {
    "id": "vanguard-vanguard-global-bond-index-fund-hedged-accumulation",
    "provider_id": "vanguard",
    "fund_name": "Vanguard Global Bond Index Fund Hedged Accumulation",
    "fund_code": null,
    "group_label": "Global bonds hedged",
    "annual_fund_fee_percent": null,
    "unit_price": null,
    "unit_price_quote_unit": "gbp",
    "source_url": "https://www.vanguardinvestor.co.uk/",
    "confidence": 60,
    "notes": "Common Vanguard UK fund/ETF glossary entry. Unit price/NAV should be refreshed from provider or quote source; platform fee is account-level."
  },
  {
    "id": "vanguard-vanguard-u-k-inflation-linked-gilt-index-fund",
    "provider_id": "vanguard",
    "fund_name": "Vanguard U.K. Inflation-Linked Gilt Index Fund",
    "fund_code": null,
    "group_label": "Index-linked gilts",
    "annual_fund_fee_percent": null,
    "unit_price": null,
    "unit_price_quote_unit": "gbp",
    "source_url": "https://www.vanguardinvestor.co.uk/",
    "confidence": 60,
    "notes": "Common Vanguard UK fund/ETF glossary entry. Unit price/NAV should be refreshed from provider or quote source; platform fee is account-level."
  },
  {
    "id": "vanguard-vanguard-esg-developed-world-all-cap-equity-index-fund",
    "provider_id": "vanguard",
    "fund_name": "Vanguard ESG Developed World All Cap Equity Index Fund",
    "fund_code": null,
    "group_label": "ESG developed equity",
    "annual_fund_fee_percent": null,
    "unit_price": null,
    "unit_price_quote_unit": "gbp",
    "source_url": "https://www.vanguardinvestor.co.uk/",
    "confidence": 60,
    "notes": "Common Vanguard UK fund/ETF glossary entry. Unit price/NAV should be refreshed from provider or quote source; platform fee is account-level."
  },
  {
    "id": "vanguard-vanguard-esg-emerging-markets-all-cap-equity-index-fund",
    "provider_id": "vanguard",
    "fund_name": "Vanguard ESG Emerging Markets All Cap Equity Index Fund",
    "fund_code": null,
    "group_label": "ESG emerging markets",
    "annual_fund_fee_percent": null,
    "unit_price": null,
    "unit_price_quote_unit": "gbp",
    "source_url": "https://www.vanguardinvestor.co.uk/",
    "confidence": 60,
    "notes": "Common Vanguard UK fund/ETF glossary entry. Unit price/NAV should be refreshed from provider or quote source; platform fee is account-level."
  },
  {
    "id": "vanguard-vanguard-global-equity-fund",
    "provider_id": "vanguard",
    "fund_name": "Vanguard Global Equity Fund",
    "fund_code": null,
    "group_label": "Global equity active",
    "annual_fund_fee_percent": null,
    "unit_price": null,
    "unit_price_quote_unit": "gbp",
    "source_url": "https://www.vanguardinvestor.co.uk/",
    "confidence": 60,
    "notes": "Common Vanguard UK fund/ETF glossary entry. Unit price/NAV should be refreshed from provider or quote source; platform fee is account-level."
  },
  {
    "id": "vanguard-vanguard-global-emerging-markets-fund",
    "provider_id": "vanguard",
    "fund_name": "Vanguard Global Emerging Markets Fund",
    "fund_code": null,
    "group_label": "Emerging markets active",
    "annual_fund_fee_percent": null,
    "unit_price": null,
    "unit_price_quote_unit": "gbp",
    "source_url": "https://www.vanguardinvestor.co.uk/",
    "confidence": 60,
    "notes": "Common Vanguard UK fund/ETF glossary entry. Unit price/NAV should be refreshed from provider or quote source; platform fee is account-level."
  },
  {
    "id": "vanguard-vanguard-active-u-k-equity-fund",
    "provider_id": "vanguard",
    "fund_name": "Vanguard Active U.K. Equity Fund",
    "fund_code": null,
    "group_label": "UK equity active",
    "annual_fund_fee_percent": null,
    "unit_price": null,
    "unit_price_quote_unit": "gbp",
    "source_url": "https://www.vanguardinvestor.co.uk/",
    "confidence": 60,
    "notes": "Common Vanguard UK fund/ETF glossary entry. Unit price/NAV should be refreshed from provider or quote source; platform fee is account-level."
  },
  {
    "id": "vanguard-vanguard-global-balanced-fund",
    "provider_id": "vanguard",
    "fund_name": "Vanguard Global Balanced Fund",
    "fund_code": null,
    "group_label": "Multi-asset",
    "annual_fund_fee_percent": null,
    "unit_price": null,
    "unit_price_quote_unit": "gbp",
    "source_url": "https://www.vanguardinvestor.co.uk/",
    "confidence": 60,
    "notes": "Common Vanguard UK fund/ETF glossary entry. Unit price/NAV should be refreshed from provider or quote source; platform fee is account-level."
  },
  {
    "id": "vanguard-vanguard-target-retirement-2030-fund",
    "provider_id": "vanguard",
    "fund_name": "Vanguard Target Retirement 2030 Fund",
    "fund_code": null,
    "group_label": "Target retirement",
    "annual_fund_fee_percent": null,
    "unit_price": null,
    "unit_price_quote_unit": "gbp",
    "source_url": "https://www.vanguardinvestor.co.uk/",
    "confidence": 60,
    "notes": "Common Vanguard UK fund/ETF glossary entry. Unit price/NAV should be refreshed from provider or quote source; platform fee is account-level."
  },
  {
    "id": "vanguard-vanguard-target-retirement-2035-fund",
    "provider_id": "vanguard",
    "fund_name": "Vanguard Target Retirement 2035 Fund",
    "fund_code": null,
    "group_label": "Target retirement",
    "annual_fund_fee_percent": null,
    "unit_price": null,
    "unit_price_quote_unit": "gbp",
    "source_url": "https://www.vanguardinvestor.co.uk/",
    "confidence": 60,
    "notes": "Common Vanguard UK fund/ETF glossary entry. Unit price/NAV should be refreshed from provider or quote source; platform fee is account-level."
  },
  {
    "id": "vanguard-vanguard-target-retirement-2040-fund",
    "provider_id": "vanguard",
    "fund_name": "Vanguard Target Retirement 2040 Fund",
    "fund_code": null,
    "group_label": "Target retirement",
    "annual_fund_fee_percent": null,
    "unit_price": null,
    "unit_price_quote_unit": "gbp",
    "source_url": "https://www.vanguardinvestor.co.uk/",
    "confidence": 60,
    "notes": "Common Vanguard UK fund/ETF glossary entry. Unit price/NAV should be refreshed from provider or quote source; platform fee is account-level."
  },
  {
    "id": "vanguard-vanguard-target-retirement-2045-fund",
    "provider_id": "vanguard",
    "fund_name": "Vanguard Target Retirement 2045 Fund",
    "fund_code": null,
    "group_label": "Target retirement",
    "annual_fund_fee_percent": null,
    "unit_price": null,
    "unit_price_quote_unit": "gbp",
    "source_url": "https://www.vanguardinvestor.co.uk/",
    "confidence": 60,
    "notes": "Common Vanguard UK fund/ETF glossary entry. Unit price/NAV should be refreshed from provider or quote source; platform fee is account-level."
  },
  {
    "id": "vanguard-vanguard-target-retirement-2050-fund",
    "provider_id": "vanguard",
    "fund_name": "Vanguard Target Retirement 2050 Fund",
    "fund_code": null,
    "group_label": "Target retirement",
    "annual_fund_fee_percent": null,
    "unit_price": null,
    "unit_price_quote_unit": "gbp",
    "source_url": "https://www.vanguardinvestor.co.uk/",
    "confidence": 60,
    "notes": "Common Vanguard UK fund/ETF glossary entry. Unit price/NAV should be refreshed from provider or quote source; platform fee is account-level."
  },

  // --- PENSIONBEE ---
  {
    "id": "pensionbee-pensionbee-tailored-plan",
    "provider_id": "pensionbee",
    "fund_name": "PensionBee Tailored Plan",
    "fund_code": null,
    "group_label": "Managed pension plan",
    "annual_fund_fee_percent": null,
    "unit_price": null,
    "unit_price_quote_unit": "gbp",
    "source_url": "https://www.pensionbee.com/uk/plans",
    "confidence": 55,
    "notes": "PensionBee charges are plan/balance based rather than simple fund-unit prices. Confirm current annual management fee from provider."
  },
  {
    "id": "pensionbee-pensionbee-tracker-plan",
    "provider_id": "pensionbee",
    "fund_name": "PensionBee Tracker Plan",
    "fund_code": null,
    "group_label": "Tracker pension plan",
    "annual_fund_fee_percent": null,
    "unit_price": null,
    "unit_price_quote_unit": "gbp",
    "source_url": "https://www.pensionbee.com/uk/plans",
    "confidence": 55,
    "notes": "PensionBee charges are plan/balance based rather than simple fund-unit prices. Confirm current annual management fee from provider."
  },
  {
    "id": "pensionbee-pensionbee-fossil-fuel-free-plan",
    "provider_id": "pensionbee",
    "fund_name": "PensionBee Fossil Fuel Free Plan",
    "fund_code": null,
    "group_label": "ESG pension plan",
    "annual_fund_fee_percent": null,
    "unit_price": null,
    "unit_price_quote_unit": "gbp",
    "source_url": "https://www.pensionbee.com/uk/plans",
    "confidence": 55,
    "notes": "PensionBee charges are plan/balance based rather than simple fund-unit prices. Confirm current annual management fee from provider."
  },
  {
    "id": "pensionbee-pensionbee-4plus-plan",
    "provider_id": "pensionbee",
    "fund_name": "PensionBee 4Plus Plan",
    "fund_code": null,
    "group_label": "Drawdown/retirement plan",
    "annual_fund_fee_percent": null,
    "unit_price": null,
    "unit_price_quote_unit": "gbp",
    "source_url": "https://www.pensionbee.com/uk/plans",
    "confidence": 55,
    "notes": "PensionBee charges are plan/balance based rather than simple fund-unit prices. Confirm current annual management fee from provider."
  },
  {
    "id": "pensionbee-pensionbee-shariah-plan",
    "provider_id": "pensionbee",
    "fund_name": "PensionBee Shariah Plan",
    "fund_code": null,
    "group_label": "Shariah pension plan",
    "annual_fund_fee_percent": null,
    "unit_price": null,
    "unit_price_quote_unit": "gbp",
    "source_url": "https://www.pensionbee.com/uk/plans",
    "confidence": 55,
    "notes": "PensionBee charges are plan/balance based rather than simple fund-unit prices. Confirm current annual management fee from provider."
  },
  {
    "id": "pensionbee-pensionbee-impact-plan",
    "provider_id": "pensionbee",
    "fund_name": "PensionBee Impact Plan",
    "fund_code": null,
    "group_label": "Impact pension plan",
    "annual_fund_fee_percent": null,
    "unit_price": null,
    "unit_price_quote_unit": "gbp",
    "source_url": "https://www.pensionbee.com/uk/plans",
    "confidence": 55,
    "notes": "PensionBee charges are plan/balance based rather than simple fund-unit prices. Confirm current annual management fee from provider."
  },
  {
    "id": "pensionbee-pensionbee-pre-annuity-plan",
    "provider_id": "pensionbee",
    "fund_name": "PensionBee Pre-Annuity Plan",
    "fund_code": null,
    "group_label": "Pre-annuity plan",
    "annual_fund_fee_percent": null,
    "unit_price": null,
    "unit_price_quote_unit": "gbp",
    "source_url": "https://www.pensionbee.com/uk/plans",
    "confidence": 55,
    "notes": "PensionBee charges are plan/balance based rather than simple fund-unit prices. Confirm current annual management fee from provider."
  },
  {
    "id": "pensionbee-pensionbee-preserve-plan",
    "provider_id": "pensionbee",
    "fund_name": "PensionBee Preserve Plan",
    "fund_code": null,
    "group_label": "Lower-risk pension plan",
    "annual_fund_fee_percent": null,
    "unit_price": null,
    "unit_price_quote_unit": "gbp",
    "source_url": "https://www.pensionbee.com/uk/plans",
    "confidence": 55,
    "notes": "PensionBee charges are plan/balance based rather than simple fund-unit prices. Confirm current annual management fee from provider."
  },

  // --- HARGREAVES LANSDOWN ---
  {
    "id": "hargreaves-lansdown-hl-portfolio-adventurous-growth",
    "provider_id": "hargreaves-lansdown",
    "fund_name": "HL Portfolio+ Adventurous Growth",
    "fund_code": null,
    "group_label": "HL ready-made portfolio",
    "annual_fund_fee_percent": null,
    "unit_price": null,
    "unit_price_quote_unit": "gbp",
    "source_url": "https://www.hl.co.uk/",
    "confidence": 45,
    "notes": "HL/platform and fund charges vary by wrapper and instrument. Refresh from provider/factsheet before accepting."
  },
  {
    "id": "hargreaves-lansdown-hl-portfolio-balanced-growth",
    "provider_id": "hargreaves-lansdown",
    "fund_name": "HL Portfolio+ Balanced Growth",
    "fund_code": null,
    "group_label": "HL ready-made portfolio",
    "annual_fund_fee_percent": null,
    "unit_price": null,
    "unit_price_quote_unit": "gbp",
    "source_url": "https://www.hl.co.uk/",
    "confidence": 45,
    "notes": "HL/platform and fund charges vary by wrapper and instrument. Refresh from provider/factsheet before accepting."
  },
  {
    "id": "hargreaves-lansdown-hl-portfolio-conservative-growth",
    "provider_id": "hargreaves-lansdown",
    "fund_name": "HL Portfolio+ Conservative Growth",
    "fund_code": null,
    "group_label": "HL ready-made portfolio",
    "annual_fund_fee_percent": null,
    "unit_price": null,
    "unit_price_quote_unit": "gbp",
    "source_url": "https://www.hl.co.uk/",
    "confidence": 45,
    "notes": "HL/platform and fund charges vary by wrapper and instrument. Refresh from provider/factsheet before accepting."
  },
  {
    "id": "hargreaves-lansdown-hl-multi-manager-uk-growth",
    "provider_id": "hargreaves-lansdown",
    "fund_name": "HL Multi-Manager UK Growth",
    "fund_code": null,
    "group_label": "HL multi-manager fund",
    "annual_fund_fee_percent": null,
    "unit_price": null,
    "unit_price_quote_unit": "gbp",
    "source_url": "https://www.hl.co.uk/",
    "confidence": 45,
    "notes": "HL/platform and fund charges vary by wrapper and instrument. Refresh from provider/factsheet before accepting."
  },
  {
    "id": "hargreaves-lansdown-hl-multi-manager-special-situations",
    "provider_id": "hargreaves-lansdown",
    "fund_name": "HL Multi-Manager Special Situations",
    "fund_code": null,
    "group_label": "HL multi-manager fund",
    "annual_fund_fee_percent": null,
    "unit_price": null,
    "unit_price_quote_unit": "gbp",
    "source_url": "https://www.hl.co.uk/",
    "confidence": 45,
    "notes": "HL/platform and fund charges vary by wrapper and instrument. Refresh from provider/factsheet before accepting."
  },
  {
    "id": "hargreaves-lansdown-hl-multi-manager-income-and-growth",
    "provider_id": "hargreaves-lansdown",
    "fund_name": "HL Multi-Manager Income and Growth",
    "fund_code": null,
    "group_label": "HL multi-manager fund",
    "annual_fund_fee_percent": null,
    "unit_price": null,
    "unit_price_quote_unit": "gbp",
    "source_url": "https://www.hl.co.uk/",
    "confidence": 45,
    "notes": "HL/platform and fund charges vary by wrapper and instrument. Refresh from provider/factsheet before accepting."
  },
  {
    "id": "hargreaves-lansdown-hl-multi-manager-european",
    "provider_id": "hargreaves-lansdown",
    "fund_name": "HL Multi-Manager European",
    "fund_code": null,
    "group_label": "HL multi-manager fund",
    "annual_fund_fee_percent": null,
    "unit_price": null,
    "unit_price_quote_unit": "gbp",
    "source_url": "https://www.hl.co.uk/",
    "confidence": 45,
    "notes": "HL/platform and fund charges vary by wrapper and instrument. Refresh from provider/factsheet before accepting."
  },
  {
    "id": "hargreaves-lansdown-hl-select-uk-growth-shares",
    "provider_id": "hargreaves-lansdown",
    "fund_name": "HL Select UK Growth Shares",
    "fund_code": null,
    "group_label": "HL Select fund",
    "annual_fund_fee_percent": null,
    "unit_price": null,
    "unit_price_quote_unit": "gbp",
    "source_url": "https://www.hl.co.uk/",
    "confidence": 45,
    "notes": "HL/platform and fund charges vary by wrapper and instrument. Refresh from provider/factsheet before accepting."
  },
  {
    "id": "hargreaves-lansdown-hl-select-global-growth-shares",
    "provider_id": "hargreaves-lansdown",
    "fund_name": "HL Select Global Growth Shares",
    "fund_code": null,
    "group_label": "HL Select fund",
    "annual_fund_fee_percent": null,
    "unit_price": null,
    "unit_price_quote_unit": "gbp",
    "source_url": "https://www.hl.co.uk/",
    "confidence": 45,
    "notes": "HL/platform and fund charges vary by wrapper and instrument. Refresh from provider/factsheet before accepting."
  },
  {
    "id": "hargreaves-lansdown-hl-select-uk-income-shares",
    "provider_id": "hargreaves-lansdown",
    "fund_name": "HL Select UK Income Shares",
    "fund_code": null,
    "group_label": "HL Select fund",
    "annual_fund_fee_percent": null,
    "unit_price": null,
    "unit_price_quote_unit": "gbp",
    "source_url": "https://www.hl.co.uk/",
    "confidence": 45,
    "notes": "HL/platform and fund charges vary by wrapper and instrument. Refresh from provider/factsheet before accepting."
  },
  {
    "id": "hargreaves-lansdown-hl-us-fund",
    "provider_id": "hargreaves-lansdown",
    "fund_name": "HL US Fund",
    "fund_code": null,
    "group_label": "HL fund",
    "annual_fund_fee_percent": null,
    "unit_price": null,
    "unit_price_quote_unit": "gbp",
    "source_url": "https://www.hl.co.uk/",
    "confidence": 45,
    "notes": "HL/platform and fund charges vary by wrapper and instrument. Refresh from provider/factsheet before accepting."
  },
  {
    "id": "hargreaves-lansdown-hl-growth-fund",
    "provider_id": "hargreaves-lansdown",
    "fund_name": "HL Growth Fund",
    "fund_code": null,
    "group_label": "HL fund",
    "annual_fund_fee_percent": null,
    "unit_price": null,
    "unit_price_quote_unit": "gbp",
    "source_url": "https://www.hl.co.uk/",
    "confidence": 45,
    "notes": "HL/platform and fund charges vary by wrapper and instrument. Refresh from provider/factsheet before accepting."
  },

  // --- AJ BELL ---
  {
    "id": "aj-bell-aj-bell-adventurous-fund",
    "provider_id": "aj-bell",
    "fund_name": "AJ Bell Adventurous Fund",
    "fund_code": null,
    "group_label": "AJ Bell funds",
    "annual_fund_fee_percent": null,
    "unit_price": null,
    "unit_price_quote_unit": "gbp",
    "source_url": "https://www.ajbell.co.uk/",
    "confidence": 45,
    "notes": "Needs provider/source refresh before relying on fee/price."
  },
  {
    "id": "aj-bell-aj-bell-balanced-fund",
    "provider_id": "aj-bell",
    "fund_name": "AJ Bell Balanced Fund",
    "fund_code": null,
    "group_label": "AJ Bell funds",
    "annual_fund_fee_percent": null,
    "unit_price": null,
    "unit_price_quote_unit": "gbp",
    "source_url": "https://www.ajbell.co.uk/",
    "confidence": 45,
    "notes": "Needs provider/source refresh before relying on fee/price."
  },
  {
    "id": "aj-bell-aj-bell-cautious-fund",
    "provider_id": "aj-bell",
    "fund_name": "AJ Bell Cautious Fund",
    "fund_code": null,
    "group_label": "AJ Bell funds",
    "annual_fund_fee_percent": null,
    "unit_price": null,
    "unit_price_quote_unit": "gbp",
    "source_url": "https://www.ajbell.co.uk/",
    "confidence": 45,
    "notes": "Needs provider/source refresh before relying on fee/price."
  },
  {
    "id": "aj-bell-aj-bell-moderately-adventurous-fund",
    "provider_id": "aj-bell",
    "fund_name": "AJ Bell Moderately Adventurous Fund",
    "fund_code": null,
    "group_label": "AJ Bell funds",
    "annual_fund_fee_percent": null,
    "unit_price": null,
    "unit_price_quote_unit": "gbp",
    "source_url": "https://www.ajbell.co.uk/",
    "confidence": 45,
    "notes": "Needs provider/source refresh before relying on fee/price."
  },
  {
    "id": "aj-bell-aj-bell-moderately-cautious-fund",
    "provider_id": "aj-bell",
    "fund_name": "AJ Bell Moderately Cautious Fund",
    "fund_code": null,
    "group_label": "AJ Bell funds",
    "annual_fund_fee_percent": null,
    "unit_price": null,
    "unit_price_quote_unit": "gbp",
    "source_url": "https://www.ajbell.co.uk/",
    "confidence": 45,
    "notes": "Needs provider/source refresh before relying on fee/price."
  },
  {
    "id": "aj-bell-aj-bell-responsible-growth-fund",
    "provider_id": "aj-bell",
    "fund_name": "AJ Bell Responsible Growth Fund",
    "fund_code": null,
    "group_label": "AJ Bell funds",
    "annual_fund_fee_percent": null,
    "unit_price": null,
    "unit_price_quote_unit": "gbp",
    "source_url": "https://www.ajbell.co.uk/",
    "confidence": 45,
    "notes": "Needs provider/source refresh before relying on fee/price."
  },
  {
    "id": "aj-bell-aj-bell-income-fund",
    "provider_id": "aj-bell",
    "fund_name": "AJ Bell Income Fund",
    "fund_code": null,
    "group_label": "AJ Bell funds",
    "annual_fund_fee_percent": null,
    "unit_price": null,
    "unit_price_quote_unit": "gbp",
    "source_url": "https://www.ajbell.co.uk/",
    "confidence": 45,
    "notes": "Needs provider/source refresh before relying on fee/price."
  },
  {
    "id": "aj-bell-aj-bell-global-growth-fund",
    "provider_id": "aj-bell",
    "fund_name": "AJ Bell Global Growth Fund",
    "fund_code": null,
    "group_label": "AJ Bell funds",
    "annual_fund_fee_percent": null,
    "unit_price": null,
    "unit_price_quote_unit": "gbp",
    "source_url": "https://www.ajbell.co.uk/",
    "confidence": 45,
    "notes": "Needs provider/source refresh before relying on fee/price."
  },
  {
    "id": "aj-bell-aj-bell-passive-adventurous-fund",
    "provider_id": "aj-bell",
    "fund_name": "AJ Bell Passive Adventurous Fund",
    "fund_code": null,
    "group_label": "AJ Bell passive funds",
    "annual_fund_fee_percent": null,
    "unit_price": null,
    "unit_price_quote_unit": "gbp",
    "source_url": "https://www.ajbell.co.uk/",
    "confidence": 45,
    "notes": "Needs provider/source refresh before relying on fee/price."
  },
  {
    "id": "aj-bell-aj-bell-passive-balanced-fund",
    "provider_id": "aj-bell",
    "fund_name": "AJ Bell Passive Balanced Fund",
    "fund_code": null,
    "group_label": "AJ Bell passive funds",
    "annual_fund_fee_percent": null,
    "unit_price": null,
    "unit_price_quote_unit": "gbp",
    "source_url": "https://www.ajbell.co.uk/",
    "confidence": 45,
    "notes": "Needs provider/source refresh before relying on fee/price."
  },

  // --- FIDELITY ---
  {
    "id": "fidelity-fidelity-multi-asset-allocator-adventurous-fund",
    "provider_id": "fidelity",
    "fund_name": "Fidelity Multi Asset Allocator Adventurous Fund",
    "fund_code": null,
    "group_label": "Fidelity multi asset",
    "annual_fund_fee_percent": null,
    "unit_price": null,
    "unit_price_quote_unit": "gbp",
    "source_url": "https://www.fidelity.co.uk/",
    "confidence": 45,
    "notes": "Needs provider/source refresh before relying on fee/price."
  },
  {
    "id": "fidelity-fidelity-multi-asset-allocator-growth-fund",
    "provider_id": "fidelity",
    "fund_name": "Fidelity Multi Asset Allocator Growth Fund",
    "fund_code": null,
    "group_label": "Fidelity multi asset",
    "annual_fund_fee_percent": null,
    "unit_price": null,
    "unit_price_quote_unit": "gbp",
    "source_url": "https://www.fidelity.co.uk/",
    "confidence": 45,
    "notes": "Needs provider/source refresh before relying on fee/price."
  },
  {
    "id": "fidelity-fidelity-multi-asset-allocator-balanced-fund",
    "provider_id": "fidelity",
    "fund_name": "Fidelity Multi Asset Allocator Balanced Fund",
    "fund_code": null,
    "group_label": "Fidelity multi asset",
    "annual_fund_fee_percent": null,
    "unit_price": null,
    "unit_price_quote_unit": "gbp",
    "source_url": "https://www.fidelity.co.uk/",
    "confidence": 45,
    "notes": "Needs provider/source refresh before relying on fee/price."
  },
  {
    "id": "fidelity-fidelity-multi-asset-allocator-defensive-fund",
    "provider_id": "fidelity",
    "fund_name": "Fidelity Multi Asset Allocator Defensive Fund",
    "fund_code": null,
    "group_label": "Fidelity multi asset",
    "annual_fund_fee_percent": null,
    "unit_price": null,
    "unit_price_quote_unit": "gbp",
    "source_url": "https://www.fidelity.co.uk/",
    "confidence": 45,
    "notes": "Needs provider/source refresh before relying on fee/price."
  },
  {
    "id": "fidelity-fidelity-index-world-fund",
    "provider_id": "fidelity",
    "fund_name": "Fidelity Index World Fund P Accumulation",
    "fund_code": "GB00BJS8SJ34", // Enriched: Exact ISIN needed for Moneybox Global Shares
    "group_label": "Global equity index",
    "annual_fund_fee_percent": 0.12,
    "unit_price": null,
    "unit_price_quote_unit": "gbp",
    "source_url": "https://www.fidelity.co.uk/",
    "confidence": 45,
    "notes": "Needs provider/source refresh before relying on fee/price."
  },
  {
    "id": "fidelity-fidelity-index-uk-fund",
    "provider_id": "fidelity",
    "fund_name": "Fidelity Index UK Fund P Accumulation",
    "fund_code": "GB00BJS8SF03", // Enriched: Institutional ISIN
    "group_label": "UK equity index",
    "annual_fund_fee_percent": 0.05,
    "unit_price": null,
    "unit_price_quote_unit": "gbp",
    "source_url": "https://www.fidelity.co.uk/",
    "confidence": 45,
    "notes": "Needs provider/source refresh before relying on fee/price."
  },
  {
    "id": "fidelity-fidelity-index-us-fund",
    "provider_id": "fidelity",
    "fund_name": "Fidelity Index US Fund P Accumulation",
    "fund_code": "GB00BJS8SH27", // Enriched: Institutional ISIN needed for Moneybox US Shares
    "group_label": "US equity index",
    "annual_fund_fee_percent": 0.05,
    "unit_price": null,
    "unit_price_quote_unit": "gbp",
    "source_url": "https://www.fidelity.co.uk/",
    "confidence": 45,
    "notes": "Needs provider/source refresh before relying on fee/price."
  },
  {
    "id": "fidelity-fidelity-index-europe-ex-uk-fund",
    "provider_id": "fidelity",
    "fund_name": "Fidelity Index Europe ex UK Fund",
    "fund_code": null,
    "group_label": "Europe equity index",
    "annual_fund_fee_percent": null,
    "unit_price": null,
    "unit_price_quote_unit": "gbp",
    "source_url": "https://www.fidelity.co.uk/",
    "confidence": 45,
    "notes": "Needs provider/source refresh before relying on fee/price."
  },
  {
    "id": "fidelity-fidelity-index-japan-fund",
    "provider_id": "fidelity",
    "fund_name": "Fidelity Index Japan Fund",
    "fund_code": null,
    "group_label": "Japan equity index",
    "annual_fund_fee_percent": null,
    "unit_price": null,
    "unit_price_quote_unit": "gbp",
    "source_url": "https://www.fidelity.co.uk/",
    "confidence": 45,
    "notes": "Needs provider/source refresh before relying on fee/price."
  },
  {
    "id": "fidelity-fidelity-index-emerging-markets-fund",
    "provider_id": "fidelity",
    "fund_name": "Fidelity Index Emerging Markets Fund P Accumulation",
    "fund_code": "GB00BHRS7Z06", // Enriched: Institutional ISIN needed for Moneybox
    "group_label": "Emerging markets index",
    "annual_fund_fee_percent": 0.20,
    "unit_price": null,
    "unit_price_quote_unit": "gbp",
    "source_url": "https://www.fidelity.co.uk/",
    "confidence": 45,
    "notes": "Needs provider/source refresh before relying on fee/price."
  },
  {
    "id": "fidelity-fidelity-global-special-situations-fund",
    "provider_id": "fidelity",
    "fund_name": "Fidelity Global Special Situations Fund",
    "fund_code": null,
    "group_label": "Global equity",
    "annual_fund_fee_percent": null,
    "unit_price": null,
    "unit_price_quote_unit": "gbp",
    "source_url": "https://www.fidelity.co.uk/",
    "confidence": 45,
    "notes": "Needs provider/source refresh before relying on fee/price."
  },
  {
    "id": "fidelity-fidelity-special-situations-fund",
    "provider_id": "fidelity",
    "fund_name": "Fidelity Special Situations Fund",
    "fund_code": null,
    "group_label": "UK equity",
    "annual_fund_fee_percent": null,
    "unit_price": null,
    "unit_price_quote_unit": "gbp",
    "source_url": "https://www.fidelity.co.uk/",
    "confidence": 45,
    "notes": "Needs provider/source refresh before relying on fee/price."
  },

  // --- AVIVA ---
  {
    "id": "aviva-aviva-pension-my-future-focus-growth",
    "provider_id": "aviva",
    "fund_name": "Aviva Pension My Future Focus Growth",
    "fund_code": null,
    "group_label": "Aviva workplace pension",
    "annual_fund_fee_percent": null,
    "unit_price": null,
    "unit_price_quote_unit": "gbp",
    "source_url": "https://www.aviva.co.uk/retirement/",
    "confidence": 40,
    "notes": "Provider fund candidate. Exact fund code, charge and unit price need source refresh before user accepts."
  },
  {
    "id": "aviva-aviva-pension-my-future-focus-consolidation",
    "provider_id": "aviva",
    "fund_name": "Aviva Pension My Future Focus Consolidation",
    "fund_code": null,
    "group_label": "Aviva workplace pension",
    "annual_fund_fee_percent": null,
    "unit_price": null,
    "unit_price_quote_unit": "gbp",
    "source_url": "https://www.aviva.co.uk/retirement/",
    "confidence": 40,
    "notes": "Provider fund candidate. Exact fund code, charge and unit price need source refresh before user accepts."
  },
  {
    "id": "aviva-aviva-pension-my-future-drawdown",
    "provider_id": "aviva",
    "fund_name": "Aviva Pension My Future Drawdown",
    "fund_code": null,
    "group_label": "Aviva workplace pension",
    "annual_fund_fee_percent": null,
    "unit_price": null,
    "unit_price_quote_unit": "gbp",
    "source_url": "https://www.aviva.co.uk/retirement/",
    "confidence": 40,
    "notes": "Provider fund candidate. Exact fund code, charge and unit price need source refresh before user accepts."
  },
  {
    "id": "aviva-aviva-stewardship-international-equity",
    "provider_id": "aviva",
    "fund_name": "Aviva Stewardship International Equity",
    "fund_code": null,
    "group_label": "Aviva stewardship",
    "annual_fund_fee_percent": null,
    "unit_price": null,
    "unit_price_quote_unit": "gbp",
    "source_url": "https://www.aviva.co.uk/retirement/",
    "confidence": 40,
    "notes": "Provider fund candidate. Exact fund code, charge and unit price need source refresh before user accepts."
  },
  {
    "id": "aviva-aviva-pension-blackrock-world-ex-uk-equity-index-tracker",
    "provider_id": "aviva",
    "fund_name": "Aviva Pension BlackRock World ex UK Equity Index Tracker",
    "fund_code": null,
    "group_label": "Aviva tracker",
    "annual_fund_fee_percent": null,
    "unit_price": null,
    "unit_price_quote_unit": "gbp",
    "source_url": "https://www.aviva.co.uk/retirement/",
    "confidence": 40,
    "notes": "Provider fund candidate. Exact fund code, charge and unit price need source refresh before user accepts."
  },

  // --- SCOTTISH WIDOWS ---
  {
    "id": "scottish-widows-scottish-widows-pension-portfolio-one",
    "provider_id": "scottish-widows",
    "fund_name": "Scottish Widows Pension Portfolio One",
    "fund_code": null,
    "group_label": "Scottish Widows pension portfolio",
    "annual_fund_fee_percent": null,
    "unit_price": null,
    "unit_price_quote_unit": "gbp",
    "source_url": "https://www.scottishwidows.co.uk/",
    "confidence": 40,
    "notes": "Provider fund candidate. Exact fund code, charge and unit price need source refresh before user accepts."
  },
  {
    "id": "scottish-widows-scottish-widows-pension-portfolio-two",
    "provider_id": "scottish-widows",
    "fund_name": "Scottish Widows Pension Portfolio Two",
    "fund_code": null,
    "group_label": "Scottish Widows pension portfolio",
    "annual_fund_fee_percent": null,
    "unit_price": null,
    "unit_price_quote_unit": "gbp",
    "source_url": "https://www.scottishwidows.co.uk/",
    "confidence": 40,
    "notes": "Provider fund candidate. Exact fund code, charge and unit price need source refresh before user accepts."
  },
  {
    "id": "scottish-widows-scottish-widows-pension-portfolio-three",
    "provider_id": "scottish-widows",
    "fund_name": "Scottish Widows Pension Portfolio Three",
    "fund_code": null,
    "group_label": "Scottish Widows pension portfolio",
    "annual_fund_fee_percent": null,
    "unit_price": null,
    "unit_price_quote_unit": "gbp",
    "source_url": "https://www.scottishwidows.co.uk/",
    "confidence": 40,
    "notes": "Provider fund candidate. Exact fund code, charge and unit price need source refresh before user accepts."
  },
  {
    "id": "scottish-widows-scottish-widows-pension-portfolio-four",
    "provider_id": "scottish-widows",
    "fund_name": "Scottish Widows Pension Portfolio Four",
    "fund_code": null,
    "group_label": "Scottish Widows pension portfolio",
    "annual_fund_fee_percent": null,
    "unit_price": null,
    "unit_price_quote_unit": "gbp",
    "source_url": "https://www.scottishwidows.co.uk/",
    "confidence": 40,
    "notes": "Provider fund candidate. Exact fund code, charge and unit price need source refresh before user accepts."
  },
  {
    "id": "scottish-widows-scottish-widows-pension-portfolio-five",
    "provider_id": "scottish-widows",
    "fund_name": "Scottish Widows Pension Portfolio Five",
    "fund_code": null,
    "group_label": "Scottish Widows pension portfolio",
    "annual_fund_fee_percent": null,
    "unit_price": null,
    "unit_price_quote_unit": "gbp",
    "source_url": "https://www.scottishwidows.co.uk/",
    "confidence": 40,
    "notes": "Provider fund candidate. Exact fund code, charge and unit price need source refresh before user accepts."
  },

  // --- ROYAL LONDON ---
  {
    "id": "royal-london-royal-london-governed-portfolio-1",
    "provider_id": "royal-london",
    "fund_name": "Royal London Governed Portfolio 1",
    "fund_code": null,
    "group_label": "Royal London governed portfolio",
    "annual_fund_fee_percent": null,
    "unit_price": null,
    "unit_price_quote_unit": "gbp",
    "source_url": "https://www.royallondon.com/",
    "confidence": 40,
    "notes": "Provider fund candidate. Exact fund code, charge and unit price need source refresh before user accepts."
  },
  {
    "id": "royal-london-royal-london-governed-portfolio-2",
    "provider_id": "royal-london",
    "fund_name": "Royal London Governed Portfolio 2",
    "fund_code": null,
    "group_label": "Royal London governed portfolio",
    "annual_fund_fee_percent": null,
    "unit_price": null,
    "unit_price_quote_unit": "gbp",
    "source_url": "https://www.royallondon.com/",
    "confidence": 40,
    "notes": "Provider fund candidate. Exact fund code, charge and unit price need source refresh before user accepts."
  },
  {
    "id": "royal-london-royal-london-governed-portfolio-3",
    "provider_id": "royal-london",
    "fund_name": "Royal London Governed Portfolio 3",
    "fund_code": null,
    "group_label": "Royal London governed portfolio",
    "annual_fund_fee_percent": null,
    "unit_price": null,
    "unit_price_quote_unit": "gbp",
    "source_url": "https://www.royallondon.com/",
    "confidence": 40,
    "notes": "Provider fund candidate. Exact fund code, charge and unit price need source refresh before user accepts."
  },
  {
    "id": "royal-london-royal-london-governed-portfolio-4",
    "provider_id": "royal-london",
    "fund_name": "Royal London Governed Portfolio 4",
    "fund_code": null,
    "group_label": "Royal London governed portfolio",
    "annual_fund_fee_percent": null,
    "unit_price": null,
    "unit_price_quote_unit": "gbp",
    "source_url": "https://www.royallondon.com/",
    "confidence": 40,
    "notes": "Provider fund candidate. Exact fund code, charge and unit price need source refresh before user accepts."
  },
  {
    "id": "royal-london-royal-london-governed-portfolio-5",
    "provider_id": "royal-london",
    "fund_name": "Royal London Governed Portfolio 5",
    "fund_code": null,
    "group_label": "Royal London governed portfolio",
    "annual_fund_fee_percent": null,
    "unit_price": null,
    "unit_price_quote_unit": "gbp",
    "source_url": "https://www.royallondon.com/",
    "confidence": 40,
    "notes": "Provider fund candidate. Exact fund code, charge and unit price need source refresh before user accepts."
  },
  {
    "id": "royal-london-royal-london-governed-retirement-income-portfolio-4",
    "provider_id": "royal-london",
    "fund_name": "Royal London Governed Retirement Income Portfolio 4",
    "fund_code": null,
    "group_label": "Royal London governed portfolio",
    "annual_fund_fee_percent": null,
    "unit_price": null,
    "unit_price_quote_unit": "gbp",
    "source_url": "https://www.royallondon.com/",
    "confidence": 40,
    "notes": "Provider fund candidate. Exact fund code, charge and unit price need source refresh before user accepts."
  },

  // --- STANDARD LIFE ---
  {
    "id": "standard-life-standard-life-sustainable-multi-asset-universal-strategic-lifestyle-profile",
    "provider_id": "standard-life",
    "fund_name": "Standard Life Sustainable Multi Asset Universal Strategic Lifestyle Profile",
    "fund_code": null,
    "group_label": "Standard Life lifestyle profile",
    "annual_fund_fee_percent": null,
    "unit_price": null,
    "unit_price_quote_unit": "gbp",
    "source_url": "https://www.standardlife.co.uk/",
    "confidence": 40,
    "notes": "Provider fund candidate. Exact fund code, charge and unit price need source refresh before user accepts."
  },
  {
    "id": "standard-life-standard-life-active-plus-iii-pension-fund",
    "provider_id": "standard-life",
    "fund_name": "Standard Life Active Plus III Pension Fund",
    "fund_code": null,
    "group_label": "Standard Life active plus",
    "annual_fund_fee_percent": null,
    "unit_price": null,
    "unit_price_quote_unit": "gbp",
    "source_url": "https://www.standardlife.co.uk/",
    "confidence": 40,
    "notes": "Provider fund candidate. Exact fund code, charge and unit price need source refresh before user accepts."
  },
  {
    "id": "standard-life-standard-life-active-plus-iv-pension-fund",
    "provider_id": "standard-life",
    "fund_name": "Standard Life Active Plus IV Pension Fund",
    "fund_code": null,
    "group_label": "Standard Life active plus",
    "annual_fund_fee_percent": null,
    "unit_price": null,
    "unit_price_quote_unit": "gbp",
    "source_url": "https://www.standardlife.co.uk/",
    "confidence": 40,
    "notes": "Provider fund candidate. Exact fund code, charge and unit price need source refresh before user accepts."
  },
  {
    "id": "standard-life-standard-life-passive-plus-iii-pension-fund",
    "provider_id": "standard-life",
    "fund_name": "Standard Life Passive Plus III Pension Fund",
    "fund_code": null,
    "group_label": "Standard Life passive plus",
    "annual_fund_fee_percent": null,
    "unit_price": null,
    "unit_price_quote_unit": "gbp",
    "source_url": "https://www.standardlife.co.uk/",
    "confidence": 40,
    "notes": "Provider fund candidate. Exact fund code, charge and unit price need source refresh before user accepts."
  },
  {
    "id": "standard-life-standard-life-passive-plus-iv-pension-fund",
    "provider_id": "standard-life",
    "fund_name": "Standard Life Passive Plus IV Pension Fund",
    "fund_code": null,
    "group_label": "Standard Life passive plus",
    "annual_fund_fee_percent": null,
    "unit_price": null,
    "unit_price_quote_unit": "gbp",
    "source_url": "https://www.standardlife.co.uk/",
    "confidence": 40,
    "notes": "Provider fund candidate. Exact fund code, charge and unit price need source refresh before user accepts."
  },

  // --- NEST ---
  {
    "id": "nest-nest-retirement-date-fund",
    "provider_id": "nest",
    "fund_name": "Nest Retirement Date Fund",
    "fund_code": null,
    "group_label": "Nest default fund",
    "annual_fund_fee_percent": null,
    "unit_price": null,
    "unit_price_quote_unit": "gbp",
    "source_url": "https://www.nestpensions.org.uk/",
    "confidence": 40,
    "notes": "Provider fund candidate. Exact fund code, charge and unit price need source refresh before user accepts."
  },
  {
    "id": "nest-nest-higher-risk-fund",
    "provider_id": "nest",
    "fund_name": "Nest Higher Risk Fund",
    "fund_code": null,
    "group_label": "Nest fund",
    "annual_fund_fee_percent": null,
    "unit_price": null,
    "unit_price_quote_unit": "gbp",
    "source_url": "https://www.nestpensions.org.uk/",
    "confidence": 40,
    "notes": "Provider fund candidate. Exact fund code, charge and unit price need source refresh before user accepts."
  },
  {
    "id": "nest-nest-sharia-fund",
    "provider_id": "nest",
    "fund_name": "Nest Sharia Fund",
    "fund_code": null,
    "group_label": "Nest fund",
    "annual_fund_fee_percent": null,
    "unit_price": null,
    "unit_price_quote_unit": "gbp",
    "source_url": "https://www.nestpensions.org.uk/",
    "confidence": 40,
    "notes": "Provider fund candidate. Exact fund code, charge and unit price need source refresh before user accepts."
  },
  {
    "id": "nest-nest-ethical-fund",
    "provider_id": "nest",
    "fund_name": "Nest Ethical Fund",
    "fund_code": null,
    "group_label": "Nest fund",
    "annual_fund_fee_percent": null,
    "unit_price": null,
    "unit_price_quote_unit": "gbp",
    "source_url": "https://www.nestpensions.org.uk/",
    "confidence": 40,
    "notes": "Provider fund candidate. Exact fund code, charge and unit price need source refresh before user accepts."
  },
  {
    "id": "nest-nest-lower-growth-fund",
    "provider_id": "nest",
    "fund_name": "Nest Lower Growth Fund",
    "fund_code": null,
    "group_label": "Nest fund",
    "annual_fund_fee_percent": null,
    "unit_price": null,
    "unit_price_quote_unit": "gbp",
    "source_url": "https://www.nestpensions.org.uk/",
    "confidence": 40,
    "notes": "Provider fund candidate. Exact fund code, charge and unit price need source refresh before user accepts."
  },
  {
    "id": "nest-nest-guided-retirement-fund",
    "provider_id": "nest",
    "fund_name": "Nest Guided Retirement Fund",
    "fund_code": null,
    "group_label": "Nest retirement fund",
    "annual_fund_fee_percent": null,
    "unit_price": null,
    "unit_price_quote_unit": "gbp",
    "source_url": "https://www.nestpensions.org.uk/",
    "confidence": 40,
    "notes": "Provider fund candidate. Exact fund code, charge and unit price need source refresh before user accepts."
  },

  // --- AEGON ---
  {
    "id": "aegon-aegon-blackrock-50-50-global-equity-index",
    "provider_id": "aegon",
    "fund_name": "Aegon BlackRock 50/50 Global Equity Index",
    "fund_code": null,
    "group_label": "Aegon insured fund",
    "annual_fund_fee_percent": null,
    "unit_price": null,
    "unit_price_quote_unit": "gbp",
    "source_url": "https://www.aegon.co.uk/",
    "confidence": 40,
    "notes": "Provider fund candidate. Exact fund code, charge and unit price need source refresh before user accepts."
  },
  {
    "id": "aegon-aegon-blackrock-world-ex-uk-equity-index",
    "provider_id": "aegon",
    "fund_name": "Aegon BlackRock World ex UK Equity Index",
    "fund_code": null,
    "group_label": "Aegon insured fund",
    "annual_fund_fee_percent": null,
    "unit_price": null,
    "unit_price_quote_unit": "gbp",
    "source_url": "https://www.aegon.co.uk/",
    "confidence": 40,
    "notes": "Provider fund candidate. Exact fund code, charge and unit price need source refresh before user accepts."
  },
  {
    "id": "aegon-aegon-blackrock-uk-equity-index",
    "provider_id": "aegon",
    "fund_name": "Aegon BlackRock UK Equity Index",
    "fund_code": null,
    "group_label": "Aegon insured fund",
    "annual_fund_fee_percent": null,
    "unit_price": null,
    "unit_price_quote_unit": "gbp",
    "source_url": "https://www.aegon.co.uk/",
    "confidence": 40,
    "notes": "Provider fund candidate. Exact fund code, charge and unit price need source refresh before user accepts."
  },
  {
    "id": "aegon-aegon-balanced-lifestyle",
    "provider_id": "aegon",
    "fund_name": "Aegon Balanced Lifestyle",
    "fund_code": null,
    "group_label": "Aegon lifestyle",
    "annual_fund_fee_percent": null,
    "unit_price": null,
    "unit_price_quote_unit": "gbp",
    "source_url": "https://www.aegon.co.uk/",
    "confidence": 40,
    "notes": "Provider fund candidate. Exact fund code, charge and unit price need source refresh before user accepts."
  },

  // --- PRUDENTIAL ---
  {
    "id": "prudential-prufund-growth-fund",
    "provider_id": "prudential",
    "fund_name": "PruFund Growth Fund",
    "fund_code": null,
    "group_label": "PruFund",
    "annual_fund_fee_percent": null,
    "unit_price": null,
    "unit_price_quote_unit": "gbp",
    "source_url": "https://www.mandg.com/pru/",
    "confidence": 40,
    "notes": "Provider fund candidate. Exact fund code, charge and unit price need source refresh before user accepts."
  },
  {
    "id": "prudential-prufund-cautious-fund",
    "provider_id": "prudential",
    "fund_name": "PruFund Cautious Fund",
    "fund_code": null,
    "group_label": "PruFund",
    "annual_fund_fee_percent": null,
    "unit_price": null,
    "unit_price_quote_unit": "gbp",
    "source_url": "https://www.mandg.com/pru/",
    "confidence": 40,
    "notes": "Provider fund candidate. Exact fund code, charge and unit price need source refresh before user accepts."
  },
  {
    "id": "prudential-prufund-risk-managed-1",
    "provider_id": "prudential",
    "fund_name": "PruFund Risk Managed 1",
    "fund_code": null,
    "group_label": "PruFund risk managed",
    "annual_fund_fee_percent": null,
    "unit_price": null,
    "unit_price_quote_unit": "gbp",
    "source_url": "https://www.mandg.com/pru/",
    "confidence": 40,
    "notes": "Provider fund candidate. Exact fund code, charge and unit price need source refresh before user accepts."
  },
  {
    "id": "prudential-prufund-risk-managed-2",
    "provider_id": "prudential",
    "fund_name": "PruFund Risk Managed 2",
    "fund_code": null,
    "group_label": "PruFund risk managed",
    "annual_fund_fee_percent": null,
    "unit_price": null,
    "unit_price_quote_unit": "gbp",
    "source_url": "https://www.mandg.com/pru/",
    "confidence": 40,
    "notes": "Provider fund candidate. Exact fund code, charge and unit price need source refresh before user accepts."
  },
  {
    "id": "prudential-prufund-risk-managed-3",
    "provider_id": "prudential",
    "fund_name": "PruFund Risk Managed 3",
    "fund_code": null,
    "group_label": "PruFund risk managed",
    "annual_fund_fee_percent": null,
    "unit_price": null,
    "unit_price_quote_unit": "gbp",
    "source_url": "https://www.mandg.com/pru/",
    "confidence": 40,
    "notes": "Provider fund candidate. Exact fund code, charge and unit price need source refresh before user accepts."
  },
  {
    "id": "prudential-prufund-risk-managed-4",
    "provider_id": "prudential",
    "fund_name": "PruFund Risk Managed 4",
    "fund_code": null,
    "group_label": "PruFund risk managed",
    "annual_fund_fee_percent": null,
    "unit_price": null,
    "unit_price_quote_unit": "gbp",
    "source_url": "https://www.mandg.com/pru/",
    "confidence": 40,
    "notes": "Provider fund candidate. Exact fund code, charge and unit price need source refresh before user accepts."
  },
  {
    "id": "prudential-prufund-risk-managed-5",
    "provider_id": "prudential",
    "fund_name": "PruFund Risk Managed 5",
    "fund_code": null,
    "group_label": "PruFund risk managed",
    "annual_fund_fee_percent": null,
    "unit_price": null,
    "unit_price_quote_unit": "gbp",
    "source_url": "https://www.mandg.com/pru/",
    "confidence": 40,
    "notes": "Provider fund candidate. Exact fund code, charge and unit price need source refresh before user accepts."
  },

  // --- ENRICHED ENTRIES REQUIRED FOR MONEYBOX & ROBO-ADVISORS ---
  // These ensure retail platforms like Moneybox can resolve to raw institutional data.
  {
    "id": "ishares-global-property-securities-equity-index-uk-d-acc",
    "provider_id": "ishares",
    "fund_name": "iShares Global Property Securities Equity Index Fund (UK) Class D Acc",
    "fund_code": "GB00B5BFJG71",
    "group_label": "Property / Real Estate",
    "annual_fund_fee_percent": 0.17,
    "unit_price": null,
    "unit_price_quote_unit": "gbp",
    "source_url": "https://www.blackrock.com/uk/individual/",
    "confidence": 95,
    "notes": "Institutional index fund used as underlying asset for retail wrappers like Moneybox Global Property Shares."
  },
  {
    "id": "ishares-overseas-corporate-bond-index-uk-d-acc",
    "provider_id": "ishares",
    "fund_name": "iShares Overseas Corporate Bond Index Fund (UK) Class D Acc",
    "fund_code": "GB00B58YKH53",
    "group_label": "Corporate bonds",
    "annual_fund_fee_percent": 0.11,
    "unit_price": null,
    "unit_price_quote_unit": "gbp",
    "source_url": "https://www.blackrock.com/uk/individual/",
    "confidence": 95,
    "notes": "Institutional index fund used for retail wrappers like Moneybox Overseas Corporate Bonds ESG."
  },
  {
    "id": "ishares-overseas-government-bond-index-uk-d-acc",
    "provider_id": "ishares",
    "fund_name": "iShares Overseas Government Bond Index Fund (UK) Class D Acc",
    "fund_code": "GB00B83Y1F47",
    "group_label": "Government bonds",
    "annual_fund_fee_percent": 0.11,
    "unit_price": null,
    "unit_price_quote_unit": "gbp",
    "source_url": "https://www.blackrock.com/uk/individual/",
    "confidence": 95,
    "notes": "Institutional index fund used for retail wrappers like Moneybox Overseas Government Bonds."
  },
  {
    "id": "legal-general-landg-pmc-global-technology-index-trust-i-acc",
    "provider_id": "legal-general",
    "fund_name": "L&G Global Technology Index Trust Class I Accumulation",
    "fund_code": "GB00B0CNH163",
    "group_label": "Global equity thematic",
    "annual_fund_fee_percent": 0.32,
    "unit_price": null,
    "unit_price_quote_unit": "gbp",
    "source_url": "https://www.legalandgeneral.com/investments/",
    "confidence": 95,
    "notes": "Institutional index fund used for retail wrappers like Moneybox Global Technology Shares."
  },
  {
    "id": "legal-general-landg-pmc-global-health-pharmaceuticals-index-trust-i-acc",
    "provider_id": "legal-general",
    "fund_name": "L&G Global Health & Pharmaceuticals Index Trust Class I Accumulation",
    "fund_code": "GB00B0CNH056",
    "group_label": "Global equity thematic",
    "annual_fund_fee_percent": 0.31,
    "unit_price": null,
    "unit_price_quote_unit": "gbp",
    "source_url": "https://www.legalandgeneral.com/investments/",
    "confidence": 95,
    "notes": "Institutional index fund used for retail wrappers like Moneybox Global Health & Pharmaceuticals Shares."
  },
  {
    "id": "hsbc-islamic-global-equity-index-fund-bc-gbp-acc",
    "provider_id": "hsbc",
    "fund_name": "HSBC Islamic Global Equity Index Fund Class BC GBP Acc",
    "fund_code": "LU2092165666",
    "group_label": "Shariah global equity",
    "annual_fund_fee_percent": 0.62,
    "unit_price": null,
    "unit_price_quote_unit": "gbp",
    "source_url": "https://www.assetmanagement.hsbc.co.uk/",
    "confidence": 95,
    "notes": "Shariah compliant institutional fund used for retail wrappers like Moneybox Islamic Global Shares."
  }
];

// ============================================================================
// --- CATALOGUE ACCESS & RESOLUTION UTILITIES ---
// ============================================================================

/**
 * Looks up a fund by its exact unique string ID.
 */
export function getProviderFundById(id: string): ProviderFund | undefined {
  return PROVIDER_FUND_CATALOGUE.find(fund => fund.id === id);
}

/**
 * Looks up a fund by its formal institutional ISIN or Ticker symbol.
 */
export function getProviderFundByCode(fundCode: string): ProviderFund | undefined {
  const cleanCode = fundCode.trim().toUpperCase();
  return PROVIDER_FUND_CATALOGUE.find(fund => 
    fund.fund_code && fund.fund_code.toUpperCase() === cleanCode
  );
}

/**
 * Flexible resolver: Finds a fund by ID first, then falls back to searching by Code,
 * and finally attempts a fuzzy match on the fund name.
 */
export function resolveProviderFund(identifier: string): ProviderFund {
  const cleanId = identifier.trim().toLowerCase();
  
  // 1. Try exact ID match
  let match = PROVIDER_FUND_CATALOGUE.find(f => f.id.toLowerCase() === cleanId);
  if (match) return match;

  // 2. Try fund code (ISIN/Ticker) match
  match = PROVIDER_FUND_CATALOGUE.find(f => f.fund_code && f.fund_code.toLowerCase() === cleanId);
  if (match) return match;

  // 3. Try exact fund name match
  match = PROVIDER_FUND_CATALOGUE.find(f => f.fund_name.toLowerCase() === cleanId);
  if (match) return match;

  throw new Error(`[Catalogue Resolution Error]: Unable to locate fund matching identifier "${identifier}".`);
}
