export const PRODUCT_IMPORT_BRIEF = {
  principle: "Match and verify before AI estimates. AI fills gaps only with confidence and source notes.",
  sourcePriority: [
    "Official retailer/API/feed or affiliate data where available",
    "Existing LOOP product library by GTIN/barcode/source URL/dedupe key",
    "Open Food Facts / barcode provider",
    "Retailer product page snapshot where permitted",
    "AI estimate only for missing nutrition/micros, clearly labelled estimated",
  ],
  importModes: [
    {
      key: "single_product_url",
      label: "Single product URL",
      use: "Best for a product page such as a ready meal or drink.",
      steps: ["fetch product page", "extract JSON-LD/meta/images", "parse ingredients/nutrition", "match existing product", "stage for review"],
    },
    {
      key: "category_url",
      label: "Category URL",
      use: "Best for Tesco meal deals / Aldi category / Lidl range pages.",
      steps: ["discover product links", "dedupe URLs", "queue each product", "polite crawl delay", "stage items in batches"],
    },
    {
      key: "csv_zip",
      label: "CSV / LOOP retailer ZIP",
      use: "Best for known catalogue imports where you already have structured files.",
      steps: ["parse import cards", "attach snapshots/allergens/servings", "normalise facts", "quality score", "review/apply"],
    },
    {
      key: "barcode_batch",
      label: "Barcode batch",
      use: "Best for scanned ready meals/products users already have.",
      steps: ["GTIN validate", "lookup existing LOOP", "lookup Open Food Facts", "stage missing data", "AI estimate gaps"],
    },
  ],
  productFields: [
    "product name",
    "brand / own-brand retailer",
    "shop tag",
    "GTIN/barcode where found",
    "category path",
    "source URL and source host",
    "image URL + image status",
    "price + price date",
    "serving size / pack size",
    "ingredients",
    "allergens: contains vs may contain",
    "macro nutrients",
    "micro nutrients where available or estimated",
    "alcohol flag / ABV where relevant",
    "confidence and source type for each fact",
  ],
  qualityChecks: [
    "has product name",
    "has image",
    "has source URL",
    "has calories/macros",
    "has serving/pack size",
    "has ingredients or clear reason missing",
    "has allergen split or clear reason missing",
    "has confidence score",
    "matched duplicate checked",
  ],
  tescoMealDealExample: [
    "Create a source job with retailer_key=tesco and source_kind=category_url.",
    "Use the meal-deal category URL as source_url.",
    "Set import_scope=food_drink.",
    "Job discovers product URLs first; it should not import directly into the live product library.",
    "Each product becomes a staged scan item with missing fields/ticks/crosses.",
    "Admin reviews low-confidence items before applying.",
  ],
};
