"use client";

import { useMemo, useState, useTransition } from "react";
import { ArrowLeft, Check, Database, ExternalLink, Loader2, Sparkles } from "lucide-react";
import { calculateRetirementPlan, type RetirementAsset, type RetirementContribution } from "@/lib/calculations/retirement";
import { saveRetirementPlan, type RetirementPlanRecord } from "@/lib/retirement/actions";
import { formatMoney } from "@/lib/format/money";
import type { RetirementAutomaticAssumptions } from "@/lib/retirement/automatic-assumptions";

type Props={personId:string;assets:RetirementAsset[];contributions?:RetirementContribution[];initialPlan?:RetirementPlanRecord|null;initialCurrentAge:number;automaticAssumptions:RetirementAutomaticAssumptions;onBack:()=>void;onSaved?:(plan:RetirementPlanRecord)=>void;};

export function RetirementPlannerPanel({personId,assets,contributions=[],initialPlan,initialCurrentAge,automaticAssumptions,onBack,onSaved}:Props){
 const [retirementAge,setRetirementAge]=useState(Number(initialPlan?.retirement_age??Math.max(initialCurrentAge+1,67)));
 const [targetAnnualIncome,setTargetAnnualIncome]=useState(Number(initialPlan?.target_annual_income??30000));
 const [growthMode,setGrowthMode]=useState<"automatic"|"manual">(initialPlan?.growth_assumption_mode??"automatic");
 const [inflationMode,setInflationMode]=useState<"automatic"|"manual">(initialPlan?.inflation_assumption_mode??"automatic");
 const [growth,setGrowth]=useState(Number(initialPlan?.growth_assumption_mode==="manual"?initialPlan.annual_growth_rate_percent:automaticAssumptions.portfolioGrowthPercent));
 const [inflation,setInflation]=useState(Number(initialPlan?.inflation_assumption_mode==="manual"?initialPlan.annual_inflation_percent:automaticAssumptions.inflationPercent));
 const [withdrawal,setWithdrawal]=useState(Number(initialPlan?.sustainable_withdrawal_rate_percent??3.5));
 const [legacyPot,setLegacyPot]=useState(Number(initialPlan?.target_legacy_pot??0));
 const [guaranteedIncome,setGuaranteedIncome]=useState(Number(initialPlan?.guaranteed_annual_income??0));
 const [saved,setSaved]=useState(Boolean(initialPlan)); const [error,setError]=useState<string|null>(null); const [isSaving,startSaving]=useTransition();
 const lifestyleAnnualTarget=useMemo(()=>Math.max(0,automaticAssumptions.currentAnnualSpending-automaticAssumptions.childcareAdjustments.filter(row=>row.endsAtAge<=retirementAge).reduce((sum,row)=>sum+row.annualAmount,0)),[automaticAssumptions,retirementAge]);
 const endingChildcareAnnual=useMemo(()=>automaticAssumptions.childcareAdjustments.filter(row=>row.endsAtAge<=retirementAge).reduce((sum,row)=>sum+row.annualAmount,0),[automaticAssumptions,retirementAge]);
 const projection=useMemo(()=>calculateRetirementPlan({currentAge:initialCurrentAge,retirementAge,targetAnnualIncome,assets,contributions,targetLegacyPot:legacyPot,guaranteedAnnualIncome:guaranteedIncome,annualGrowthRatePercent:growth,annualInflationPercent:inflation,sustainableWithdrawalRatePercent:withdrawal}),[initialCurrentAge,retirementAge,targetAnnualIncome,assets,contributions,legacyPot,guaranteedIncome,growth,inflation,withdrawal]);
 function dirty(){setSaved(false)}
 function useAutomaticGrowth(){setGrowthMode("automatic");setGrowth(automaticAssumptions.portfolioGrowthPercent);dirty()}
 function useAutomaticInflation(){setInflationMode("automatic");setInflation(automaticAssumptions.inflationPercent);dirty()}
 function save(){setError(null);startSaving(async()=>{try{const plan=await saveRetirementPlan({personId,scope:"person",retirementAge,targetAnnualIncome,targetLegacyPot:legacyPot,annualGrowthRatePercent:growth,annualInflationPercent:inflation,sustainableWithdrawalRatePercent:withdrawal,guaranteedAnnualIncome:guaranteedIncome,growthAssumptionMode:growthMode,inflationAssumptionMode:inflationMode,assumptionSnapshot:{portfolioGrowthPercent:automaticAssumptions.portfolioGrowthPercent,inflationPercent:automaticAssumptions.inflationPercent,inflationAsOfDate:automaticAssumptions.inflationAsOfDate,fundEvidence:automaticAssumptions.fundEvidence.map(row=>({pensionFundId:row.pensionFundId,fiveYearPercent:row.fiveYearPercent,tenYearPercent:row.tenYearPercent,asOfDate:row.asOfDate}))}});setSaved(true);onSaved?.(plan);}catch(e){setError(e instanceof Error?e.message:"Could not save your retirement plan.")}})}
 return <section className="space-y-5">
  <div className="flex flex-wrap items-center justify-between gap-3"><div className="flex items-center gap-3"><button type="button" onClick={onBack} className="grid h-11 w-11 place-items-center rounded-full border border-slate-200 bg-white text-slate-700"><ArrowLeft className="h-5 w-5"/></button><div><p className="text-xs font-black uppercase tracking-[0.18em] text-slate-400">Retirement planning</p><h1 className="text-3xl font-black text-slate-950">Shape the retirement you want</h1></div></div><button type="button" onClick={save} disabled={isSaving} className="inline-flex items-center gap-2 rounded-full bg-slate-950 px-5 py-3 text-sm font-black text-white disabled:opacity-60">{isSaving?<Loader2 className="h-4 w-4 animate-spin"/>:saved?<Check className="h-4 w-4"/>:null}{isSaving?"Saving…":saved?"Saved":"Save plan"}</button></div>
  {error?<div className="rounded-2xl bg-red-50 px-4 py-3 text-sm font-bold text-red-700">{error}</div>:null}
  <div className="grid gap-5 xl:grid-cols-[0.9fr_1.1fr]">
   <div className="rounded-[2rem] border border-slate-200 bg-white p-6 shadow-sm"><div className="space-y-6">
    <div><p className="text-sm font-black text-slate-700">Current age</p><p className="mt-2 text-2xl font-black text-slate-950">{initialCurrentAge}</p><p className="mt-1 text-xs font-semibold text-slate-400">Pulled from the person&apos;s date of birth in LOOP.</p></div>
    <label className="block"><span className="flex items-center justify-between text-sm font-black text-slate-700"><span>I want to retire at</span><span>{retirementAge}</span></span><input type="range" min={Math.max(initialCurrentAge,40)} max={80} value={retirementAge} onChange={e=>{setRetirementAge(Number(e.target.value));dirty()}} className="mt-3 w-full"/></label>
    <label className="block"><span className="text-sm font-black text-slate-700">Income I want in retirement</span><div className="mt-2 flex items-center rounded-2xl border border-slate-200 px-4"><span className="font-black text-slate-400">£</span><input type="number" min={0} step={1000} value={targetAnnualIncome} onChange={e=>{setTargetAnnualIncome(Number(e.target.value));dirty()}} className="w-full border-0 px-2 py-3 font-bold outline-none"/><span className="text-sm font-bold text-slate-400">/ year</span></div><p className="mt-2 text-xs font-semibold text-slate-400">Expressed in today&apos;s money.</p></label>
    {lifestyleAnnualTarget>0?<button type="button" onClick={()=>{setTargetAnnualIncome(Math.round(lifestyleAnnualTarget/100)*100);dirty()}} className="w-full rounded-2xl border border-emerald-200 bg-emerald-50 p-4 text-left"><span className="flex items-center gap-2 text-xs font-black uppercase tracking-wide text-emerald-700"><Sparkles className="h-4 w-4"/>Maintain tracked lifestyle</span><span className="mt-2 block text-2xl font-black text-emerald-950">{formatMoney(lifestyleAnnualTarget)} / year</span><span className="mt-1 block text-xs font-semibold leading-5 text-emerald-800">Current tracked spending, excluding savings{endingChildcareAnnual>0?` and ${formatMoney(endingChildcareAnnual)} of annual childcare expected to end by age ${retirementAge}`:""}. Use as target.</span></button>:null}
    <details className="rounded-2xl bg-slate-50 p-4"><summary className="cursor-pointer text-sm font-black text-slate-700">Advanced assumptions</summary><div className="mt-4 grid gap-4 sm:grid-cols-2">
      <label><span className="flex items-center justify-between text-xs font-black text-slate-500"><span>Growth %</span><button type="button" onClick={useAutomaticGrowth} className={growthMode==="automatic"?"text-emerald-700":"text-violet-700"}>{growthMode==="automatic"?"Automatic":"Use evidence"}</button></span><input type="number" step={0.1} value={growth} onChange={e=>{setGrowthMode("manual");setGrowth(Number(e.target.value));dirty()}} className="mt-1 w-full rounded-xl border border-slate-200 px-3 py-2 font-bold"/><span className="mt-1 block text-[11px] font-semibold text-slate-400">{growthMode==="automatic"?`${automaticAssumptions.fundEvidence.filter(row=>row.planningRatePercent!=null).length} fund histories · value weighted`:"Manual override"}</span></label>
      <label><span className="flex items-center justify-between text-xs font-black text-slate-500"><span>Inflation %</span><button type="button" onClick={useAutomaticInflation} className={inflationMode==="automatic"?"text-emerald-700":"text-violet-700"}>{inflationMode==="automatic"?"Automatic":"Use prevailing"}</button></span><input type="number" step={0.1} value={inflation} onChange={e=>{setInflationMode("manual");setInflation(Number(e.target.value));dirty()}} className="mt-1 w-full rounded-xl border border-slate-200 px-3 py-2 font-bold"/><a href={automaticAssumptions.inflationSourceUrl} target="_blank" rel="noreferrer" className="mt-1 inline-flex items-center gap-1 text-[11px] font-semibold text-slate-400 hover:text-violet-700">{automaticAssumptions.inflationPeriodYears}-year prevailing CPIH · {automaticAssumptions.inflationAsOfDate?.slice(0,4)??"fallback"}<ExternalLink className="h-3 w-3"/></a></label>
      <label><span className="text-xs font-black text-slate-500">Withdrawal %</span><input type="number" step={0.1} value={withdrawal} onChange={e=>{setWithdrawal(Number(e.target.value));dirty()}} className="mt-1 w-full rounded-xl border border-slate-200 px-3 py-2 font-bold"/></label>
      <label><span className="text-xs font-black text-slate-500">Legacy pot £</span><input type="number" step={1000} value={legacyPot} onChange={e=>{setLegacyPot(Number(e.target.value));dirty()}} className="mt-1 w-full rounded-xl border border-slate-200 px-3 py-2 font-bold"/></label>
      <label><span className="text-xs font-black text-slate-500">Guaranteed income £/yr</span><input type="number" step={1000} value={guaranteedIncome} onChange={e=>{setGuaranteedIncome(Number(e.target.value));dirty()}} className="mt-1 w-full rounded-xl border border-slate-200 px-3 py-2 font-bold"/></label>
    </div></details>
   </div></div>
   <div className="space-y-5"><div className="rounded-[2rem] bg-slate-950 p-7 text-white"><p className="text-xs font-black uppercase tracking-[0.18em] text-slate-400">Projected at age {retirementAge}</p><p className="mt-3 text-5xl font-black tracking-tight">{formatMoney(projection.projectedRetirementAssetsTodayMoney)}</p><p className="mt-2 text-sm font-semibold text-slate-400">In today&apos;s money</p><div className="mt-7 grid gap-3 sm:grid-cols-3"><div className="rounded-2xl bg-white/10 p-4"><p className="text-xs font-black uppercase tracking-wide text-slate-400">Sustainable income</p><p className="mt-2 text-xl font-black">{formatMoney(projection.projectedAnnualIncomeTodayMoney)} / year</p></div><div className="rounded-2xl bg-white/10 p-4"><p className="text-xs font-black uppercase tracking-wide text-slate-400">Target</p><p className="mt-2 text-xl font-black">{formatMoney(targetAnnualIncome)} / year</p></div><div className="rounded-2xl bg-white/10 p-4"><p className="text-xs font-black uppercase tracking-wide text-slate-400">Required drawdown</p><p className={`mt-2 text-xl font-black ${projection.requiredDrawdownRatePercent!=null&&projection.requiredDrawdownRatePercent>withdrawal?"text-amber-300":"text-emerald-300"}`}>{projection.requiredDrawdownRatePercent==null?"—":`${projection.requiredDrawdownRatePercent.toFixed(1)}% / year`}</p><p className="mt-1 text-xs font-semibold text-slate-400">Model uses {withdrawal.toFixed(1)}% sustainable</p></div></div></div>
    <div className={`rounded-[2rem] p-6 ${projection.status==="on_track"?"bg-emerald-50":"bg-amber-50"}`}><p className={`text-xs font-black uppercase tracking-[0.18em] ${projection.status==="on_track"?"text-emerald-700":"text-amber-700"}`}>{projection.status==="on_track"?"You are on track":"Your current gap"}</p><p className={`mt-2 text-3xl font-black ${projection.status==="on_track"?"text-emerald-900":"text-amber-900"}`}>{projection.status==="on_track"?"Target reached":`${formatMoney(projection.annualIncomeGapTodayMoney)} / year`}</p>{projection.status!=="on_track"&&Number.isFinite(projection.requiredAdditionalMonthlyContributionTodayMoney)?<p className="mt-3 text-sm font-bold leading-6 text-amber-800">Around <strong>{formatMoney(projection.requiredAdditionalMonthlyContributionTodayMoney)} more per month</strong> could close the modelled gap by age {retirementAge}.</p>:null}</div>
    <div className="rounded-[2rem] border border-slate-200 bg-white p-6"><p className="text-sm font-black text-slate-800">What LOOP is using</p><div className="mt-4 space-y-3">{projection.assetProjections.map(asset=><div key={asset.id} className="flex items-center justify-between gap-4 border-b border-slate-100 pb-3 last:border-0"><div><p className="font-black text-slate-700">{asset.label}</p><p className="text-xs font-semibold text-slate-400">{asset.accessibleAtRetirement?"Available by retirement":`Not accessible at ${retirementAge}`}{asset.annualGrowthRatePercent!=null?` · ${asset.annualGrowthRatePercent.toFixed(1)}% evidenced growth`:" · planning fallback"}</p></div><p className="font-black text-slate-800">{formatMoney(asset.projectedValueAtRetirementTodayMoney)}</p></div>)}</div></div>
    <details className="rounded-[2rem] border border-slate-200 bg-white p-6"><summary className="flex cursor-pointer list-none items-center gap-2 text-sm font-black text-slate-800"><Database className="h-4 w-4 text-violet-600"/>Fund return evidence</summary><div className="mt-4 space-y-3">{automaticAssumptions.fundEvidence.map(row=><div key={row.pensionFundId} className="grid gap-2 border-b border-slate-100 pb-3 text-sm sm:grid-cols-[1fr_auto_auto_auto]"><div><p className="font-black text-slate-700">{row.fundName}</p><p className="text-xs font-semibold text-slate-400">{row.asOfDate?`Through ${row.asOfDate}`:"History still building"}</p></div><p className="font-bold text-slate-600">5y {row.fiveYearPercent==null?"—":`${row.fiveYearPercent.toFixed(1)}% pa`}</p><p className="font-bold text-slate-600">10y {row.tenYearPercent==null?"—":`${row.tenYearPercent.toFixed(1)}% pa`}</p><p className="font-black text-emerald-700">Plan {row.planningRatePercent==null?"—":`${row.planningRatePercent.toFixed(1)}%`}</p></div>)}{!automaticAssumptions.fundEvidence.length?<p className="text-sm font-semibold text-slate-500">Add and verify a pension fund to build source-backed return evidence.</p>:null}<p className="text-xs font-semibold leading-5 text-slate-400">Past performance is evidence, not a guarantee. LOOP stores the genuine annualised history, weights funds by current value and caps the automatic intermediate planning rate at 5% rather than projecting exceptional returns indefinitely.</p></div></details>
   </div>
  </div>
 </section>
}
