"use server";

import { revalidatePath } from "next/cache";
import { createClient } from "@/lib/supabase/server";

function clean(value: FormDataEntryValue | null) {
  return String(value || "").trim();
}

function sqlQuote(value: string | null | undefined) {
  if (!value) return "null";
  return `'${String(value).replaceAll("'", "''")}'`;
}

function inferMarket(input: string) {
  const text = input.trim();
  const upper = text.toUpperCase();
  const known: Record<string, { name: string; country: string; currency: string }> = {
    LSE: { name: "London Stock Exchange", country: "GB", currency: "GBP" },
    AIM: { name: "Alternative Investment Market", country: "GB", currency: "GBP" },
    NASDAQ: { name: "Nasdaq", country: "US", currency: "USD" },
    NYSE: { name: "New York Stock Exchange", country: "US", currency: "USD" },
    TSX: { name: "Toronto Stock Exchange", country: "CA", currency: "CAD" },
    ASX: { name: "Australian Securities Exchange", country: "AU", currency: "AUD" },
    EURONEXT: { name: "Euronext", country: "EU", currency: "EUR" },
  };

  const knownKey = Object.keys(known).find((key) => upper.includes(key));
  if (knownKey) return { code: knownKey, ...known[knownKey] };

  const code = (upper.match(/\b[A-Z]{2,8}\b/)?.[0] || upper.replace(/[^A-Z0-9]/g, "").slice(0, 8) || "NEW").slice(0, 12);
  const name = text.replace(/^add\s+/i, "").replace(/^market\s+/i, "").slice(0, 120) || code;
  return { code, name, country: "", currency: "" };
}

function buildCoverageSql(args: { code: string; name: string; country: string; currency: string; prompt: string }) {
  const sourceName = `${args.code} coverage`;
  return `-- Generated by LOOP admin investment coverage assistant\ninsert into public.loop_investment_markets(market_code, market_name, country_code, currency_code, coverage_status, requested_reason, ai_next_update_note)\nvalues (${sqlQuote(args.code)}, ${sqlQuote(args.name)}, ${sqlQuote(args.country || null)}, ${sqlQuote(args.currency || null)}, 'planned', ${sqlQuote(args.prompt)}, ${sqlQuote(`Add ${args.code} coverage and confirm symbols/provider mapping.`)})\non conflict (market_code) do update set\n  market_name = excluded.market_name,\n  country_code = coalesce(excluded.country_code, public.loop_investment_markets.country_code),\n  currency_code = coalesce(excluded.currency_code, public.loop_investment_markets.currency_code),\n  coverage_status = 'planned',\n  ai_next_update_note = excluded.ai_next_update_note,\n  updated_at = now();\n\ninsert into public.loop_investment_coverage_sources(source_name, source_kind, markets, checks_stocks, check_frequency_minutes, enabled, notes)\nvalues (${sqlQuote(sourceName)}, 'admin_list', array[${sqlQuote(args.code)}]::text[], true, 1440, true, ${sqlQuote(`Created from admin request: ${args.prompt}`)})\non conflict do nothing;`;
}

export async function createInvestmentCoveragePlan(formData: FormData) {
  const supabase = await createClient();
  const { data: userData } = await supabase.auth.getUser();

  const prompt = clean(formData.get("coverage_prompt"));
  if (!prompt) throw new Error("Tell the coverage assistant what market/source to add.");

  const inferred = inferMarket(prompt);
  const code = clean(formData.get("market_code_override")) || inferred.code;
  const name = clean(formData.get("market_name_override")) || inferred.name;
  const country = (clean(formData.get("country_code_override")) || inferred.country).toUpperCase();
  const currency = (clean(formData.get("currency_code_override")) || inferred.currency).toUpperCase();
  const generatedSql = buildCoverageSql({ code, name, country, currency, prompt });

  const { error: marketError } = await supabase.from("loop_investment_markets").upsert({
    market_code: code,
    market_name: name,
    country_code: country || null,
    currency_code: currency || null,
    enabled: true,
    coverage_status: "covered",
    requested_by: userData.user?.id || null,
    requested_reason: prompt,
    ai_next_update_note: `Saved from Admin coverage planner for ${code}. Review provider mapping if live pricing needs a paid feed.`,
    updated_at: new Date().toISOString(),
  }, { onConflict: "market_code" });

  if (marketError) throw new Error(marketError.message);

  const sourceName = `${code} coverage`;
  const { data: existingSource } = await supabase
    .from("loop_investment_coverage_sources")
    .select("id")
    .eq("source_name", sourceName)
    .limit(1)
    .maybeSingle();

  if (existingSource?.id) {
    await supabase.from("loop_investment_coverage_sources").update({
      source_kind: "admin_list",
      markets: [code],
      checks_stocks: true,
      check_frequency_minutes: 1440,
      enabled: true,
      notes: `Saved from admin request: ${prompt}`,
      updated_at: new Date().toISOString(),
    }).eq("id", existingSource.id);
  } else {
    await supabase.from("loop_investment_coverage_sources").insert({
      source_name: sourceName,
      source_kind: "admin_list",
      markets: [code],
      checks_stocks: true,
      check_frequency_minutes: 1440,
      enabled: true,
      notes: `Saved from admin request: ${prompt}`,
    });
  }

  // This table is introduced in v27.82. If the migration has not been run yet,
  // the market/source rows above still get saved.
  await supabase.from("loop_investment_ai_market_requests").insert({
    prompt,
    inferred_market_code: code,
    inferred_market_name: name,
    inferred_country_code: country || null,
    inferred_currency_code: currency || null,
    generated_sql: generatedSql,
    status: "sql_generated",
    created_by: userData.user?.id || null,
  });

  await supabase.rpc("loop_admin_raise_alert", {
    p_area: "investment_coverage",
    p_severity: "medium",
    p_alert_key: "investment_market_ai_plan",
    p_title: "Investment coverage AI plan generated",
    p_summary: `${code} - ${name}`,
    p_detail: "Admin requested market/source coverage; generated SQL is available on the investment coverage page.",
    p_entity_kind: "investment_market",
    p_entity_id: code,
    p_action_url: "/admin/investment-coverage",
    p_payload: { market_code: code, market_name: name, generated_sql: generatedSql },
    p_check_cadence_minutes: 1440,
  });

  revalidatePath("/admin/investment-coverage");
}

export async function addInvestmentMarket(formData: FormData) {
  const supabase = await createClient();
  const { data: userData } = await supabase.auth.getUser();

  const marketCode = String(formData.get("market_code") || "").toUpperCase().trim();
  const marketName = String(formData.get("market_name") || "").trim();

  const { error } = await supabase.from("loop_investment_markets").insert({
    market_code: marketCode,
    market_name: marketName,
    country_code: String(formData.get("country_code") || "").toUpperCase().trim() || null,
    currency_code: String(formData.get("currency_code") || "").toUpperCase().trim() || null,
    coverage_status: "planned",
    requested_by: userData.user?.id || null,
    requested_reason: String(formData.get("requested_reason") || ""),
    ai_next_update_note: `Add market ${marketCode} (${marketName}) to the next investment coverage update.`,
  });

  if (error) throw new Error(error.message);

  await supabase.rpc("loop_admin_raise_alert", {
    p_area: "investment_coverage",
    p_severity: "medium",
    p_alert_key: "investment_market_requested",
    p_title: "Investment market requested",
    p_summary: `${marketCode} - ${marketName}`,
    p_detail: "AI should add this market/source coverage to a future update.",
    p_entity_kind: "investment_market",
    p_entity_id: marketCode,
    p_action_url: "/admin/investment-coverage",
    p_payload: { market_code: marketCode, market_name: marketName },
    p_check_cadence_minutes: 1440,
  });

  revalidatePath("/admin/investment-coverage");
}
