import Link from "next/link";
import { redirect } from "next/navigation";
import { BellRing, CheckCircle2, Info, Plus, Trash2 } from "lucide-react";
import { SectionCard } from "@/components/SectionCard";
import { StatCard } from "@/components/StatCard";
import { createClient } from "@/lib/supabase/server";
import { createTestNotification, dismissNotification, markNotificationRead } from "./actions";

async function requireUser() {
  const supabase = await createClient();
  const { data: { user } } = await supabase.auth.getUser();
  if (!user) redirect("/login");
  return { supabase, user };
}

function tone(status: string, severity: string) {
  if (status === "read") return "border-slate-200 bg-white/70";
  if (severity === "urgent") return "border-red-200 bg-red-50/80";
  if (severity === "warning") return "border-orange-200 bg-orange-50/80";
  if (severity === "success") return "border-emerald-200 bg-emerald-50/80";
  return "border-blue-100 bg-blue-50/80";
}

export default async function NotificationsPage() {
  const { supabase, user } = await requireUser();
  const { data: notifications } = await supabase
    .from("app_notifications")
    .select("*")
    .eq("user_id", user.id)
    .neq("status", "dismissed")
    .order("created_at", { ascending: false })
    .limit(80);

  const unread = (notifications || []).filter((n: any) => n.status === "unread").length;
  const urgent = (notifications || []).filter((n: any) => n.severity === "urgent" || n.severity === "warning").length;

  return (
    <main className="mx-auto max-w-7xl space-y-8 px-4 py-8 md:px-6">
      <section className="relative overflow-hidden rounded-[2rem] bg-slate-950 p-7 text-white shadow-[0_30px_120px_-70px_rgba(15,23,42,.9)]">
        <div className="absolute -right-20 -top-20 h-64 w-64 rounded-full bg-blue-500/30 blur-3xl" />
        <div className="relative flex flex-col gap-5 lg:flex-row lg:items-end lg:justify-between">
          <div>
            <div className="mb-4 inline-flex items-center gap-2 rounded-full border border-white/15 bg-white/10 px-3 py-1 text-xs font-black uppercase tracking-wide text-white/80">
              <BellRing className="h-4 w-4" /> Notification hub
            </div>
            <h1 className="text-4xl font-black tracking-tight">Useful nudges, not noise</h1>
            <p className="mt-2 max-w-3xl text-sm font-medium text-white/70">Spending patterns, savings forecasts, renewal checks and food/health reminders can land here before going to email or push.</p>
          </div>
          <form action={createTestNotification}>
            <button className="inline-flex items-center gap-2 rounded-full bg-white px-5 py-3 text-sm font-black text-slate-950"><Plus className="h-4 w-4" /> Create test notification</button>
          </form>
        </div>
      </section>

      <div className="grid gap-4 md:grid-cols-3">
        <StatCard title="Unread" value={String(unread)} helper="Items waiting for you" />
        <StatCard title="Needs attention" value={String(urgent)} helper="Warnings/urgent nudges" />
        <StatCard title="Total active" value={String((notifications || []).length)} helper="Not dismissed" />
      </div>

      <SectionCard title="Latest notifications" description="Messages are generated by admin templates, scheduled jobs and future app events.">
        <div className="space-y-3">
          {(notifications || []).length === 0 ? (
            <div className="rounded-3xl border border-dashed border-slate-300 bg-slate-50 p-6 text-sm font-bold text-slate-500">
              No notifications yet. Create a test notification or configure digest rules from Admin.
            </div>
          ) : null}
          {(notifications || []).map((notification: any) => (
            <article key={notification.id} className={`rounded-3xl border p-5 ${tone(notification.status, notification.severity)}`}>
              <div className="flex flex-col gap-4 lg:flex-row lg:items-start lg:justify-between">
                <div className="flex gap-3">
                  <span className="grid h-11 w-11 flex-none place-items-center rounded-2xl bg-white text-slate-700 shadow-sm">
                    {notification.status === "read" ? <CheckCircle2 className="h-5 w-5" /> : <Info className="h-5 w-5" />}
                  </span>
                  <div>
                    <div className="flex flex-wrap items-center gap-2">
                      <h2 className="font-black text-slate-950">{notification.title}</h2>
                      <span className="rounded-full bg-white/80 px-2 py-1 text-[11px] font-black uppercase text-slate-500">{notification.notification_type}</span>
                      <span className="rounded-full bg-white/80 px-2 py-1 text-[11px] font-black uppercase text-slate-500">{notification.severity}</span>
                    </div>
                    {notification.body ? <p className="mt-2 text-sm font-medium text-slate-600">{notification.body}</p> : null}
                    <p className="mt-2 text-xs font-bold text-slate-400">{new Date(notification.created_at).toLocaleString("en-GB")}</p>
                    {notification.cta_href ? <Link href={notification.cta_href} className="mt-3 inline-flex rounded-full bg-slate-950 px-4 py-2 text-xs font-black text-white">{notification.cta_label || "Open"}</Link> : null}
                  </div>
                </div>
                <div className="flex gap-2">
                  {notification.status !== "read" ? (
                    <form action={markNotificationRead}>
                      <input type="hidden" name="id" value={notification.id} />
                      <button className="rounded-full border border-slate-200 bg-white px-3 py-2 text-xs font-black text-slate-700">Mark read</button>
                    </form>
                  ) : null}
                  <form action={dismissNotification}>
                    <input type="hidden" name="id" value={notification.id} />
                    <button className="inline-flex items-center gap-1 rounded-full border border-red-100 bg-white px-3 py-2 text-xs font-black text-red-600"><Trash2 className="h-4 w-4" /> Dismiss</button>
                  </form>
                </div>
              </div>
            </article>
          ))}
        </div>
      </SectionCard>
    </main>
  );
}
