import Link from "next/link";
import { Nav } from "@/components/Nav";
import { HouseShell } from "@/components/mortgage/HouseShell";
import { calculateMonthlyMortgagePayment } from "@/lib/calculations/mortgage";
import { formatMoney } from "@/lib/format/money";
import { houseValue, loadHouseCore } from "./house-page-data";

async function Content(){
  const {homes,deals,valuations}=await loadHouseCore();
  const home=homes.find(h=>h.ownership_status==="current_home")??homes[0];
  const deal=deals.find(d=>d.home_id===home?.id)??deals[0];
  const value=houseValue(home,valuations), balance=Number(deal?.balance||0), ltv=value>0?(balance/value)*100:0, equity=Math.max(0,value-balance);
  const payment=Number(deal?.monthly_payment_override||0)||(deal&&balance?calculateMonthlyMortgagePayment({balance,annualInterestRate:Number(deal.interest_rate||0),termYears:Number(deal.term_years||25)}):0);
  return <HouseShell homes={homes} deals={deals} valuations={valuations}><div className="space-y-5">
    <header><p className="text-xs font-black uppercase tracking-[0.16em] text-violet-600">House overview</p><h1 className="mt-1 text-4xl font-black tracking-tight text-slate-950">Your home, in one place</h1><p className="mt-2 max-w-3xl text-sm font-semibold leading-6 text-slate-500">See your property, mortgage and key home insights at a glance.</p></header>
    <section className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4">{[["Home value",formatMoney(value),"Latest tracked estimate"],["Mortgage balance",formatMoney(balance),`${ltv.toFixed(0)}% LTV`],["Monthly payment",formatMoney(payment),"Current stored payment"],["Equity",formatMoney(equity),value?`${Math.max(0,100-ltv).toFixed(0)}% of value`:"Add valuation"]].map(([l,m,h])=><article key={l} className="rounded-2xl border border-slate-200 bg-white p-4 shadow-sm"><p className="text-[10px] font-black uppercase tracking-[0.11em] text-slate-400">{l}</p><p className="mt-2 text-2xl font-black text-slate-950">{m}</p><p className="mt-1 text-[11px] font-semibold text-slate-500">{h}</p></article>)}</section>
    <section className="overflow-hidden rounded-[1.6rem] border border-slate-200 bg-white shadow-sm"><div className="grid lg:grid-cols-[1.15fr_.85fr]">
      <div className="relative min-h-[330px] overflow-hidden bg-gradient-to-br from-sky-100 via-slate-50 to-violet-100">{home?.latitude&&home?.longitude?<iframe title={`${home.label} map`} src={`https://www.openstreetmap.org/export/embed.html?bbox=${Number(home.longitude)-0.01}%2C${Number(home.latitude)-0.006}%2C${Number(home.longitude)+0.01}%2C${Number(home.latitude)+0.006}&layer=mapnik&marker=${home.latitude}%2C${home.longitude}`} className="absolute inset-0 h-full w-full border-0" loading="lazy"/>:<div className="absolute inset-0 grid place-items-center text-6xl">🏠</div>}<div className="absolute inset-x-4 bottom-4 grid gap-2 sm:grid-cols-3">{[["Current home",home?.label||"Add a home"],["Home value",formatMoney(value)],["Mortgage",`${formatMoney(balance)} · ${ltv.toFixed(1)}% LTV`]].map(([l,t])=><div key={l} className="rounded-xl bg-white/95 p-3 shadow-lg backdrop-blur"><p className="text-[10px] font-black uppercase text-slate-400">{l}</p><p className="mt-1 truncate text-sm font-black text-slate-950">{t}</p></div>)}</div></div>
      <div className="p-5 sm:p-6"><p className="text-xs font-black uppercase tracking-[0.14em] text-violet-600">Mortgage summary</p><h2 className="mt-2 text-2xl font-black text-slate-950">{deal?.lender||"No mortgage added"}</h2><p className="mt-1 text-sm font-semibold text-slate-500">{deal?.product_name||"Add your mortgage details to unlock rate planning."}</p><div className="mt-5 grid gap-3 sm:grid-cols-2"><div className="rounded-xl bg-slate-50 p-4"><p className="text-[10px] font-black uppercase text-slate-400">Rate</p><p className="mt-1 text-2xl font-black text-slate-950">{deal?`${Number(deal.interest_rate||0).toFixed(2)}%`:"—"}</p></div><div className="rounded-xl bg-slate-50 p-4"><p className="text-[10px] font-black uppercase text-slate-400">Payment</p><p className="mt-1 text-2xl font-black text-slate-950">{formatMoney(payment)}</p></div></div><div className="mt-5 flex flex-wrap gap-2"><Link href="/mortgage/property" className="rounded-xl bg-slate-950 px-4 py-2.5 text-xs font-black text-white">View property</Link><Link href="/mortgage/rates" className="rounded-xl border border-violet-200 bg-violet-50 px-4 py-2.5 text-xs font-black text-violet-700">Mortgage & rates</Link></div></div>
    </div></section>
    <section className="grid gap-3 md:grid-cols-2 xl:grid-cols-4">{[["/mortgage/rates","Deal expiry soon",deal?.initial_period_end?`Current deal ends ${deal.initial_period_end}.`:"Add a deal-end date to track this.","Review rates"],["/mortgage/rates","Potential saving","Compare the live mortgage with market benchmarks and imported lender quotes.","Compare rates"],["/affordability","Affordability check","See how the mortgage fits with household income and outgoings.","Check affordability"],["/mortgage/moving-costs","Moving home","Track searches, stamp duty and moving costs separately.","Plan move"]].map(([href,title,copy,action])=><Link key={title} href={href} className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm hover:border-violet-200"><p className="text-sm font-black text-slate-950">{title}</p><p className="mt-2 min-h-[3rem] text-xs font-semibold leading-5 text-slate-500">{copy}</p><p className="mt-4 text-xs font-black text-violet-700">{action} →</p></Link>)}</section>
  </div></HouseShell>;
}
export default function HouseHomePage(){return <><Nav/><Content/></>}
