import Link from "next/link";
import { Nav } from "@/components/Nav";
import { HouseShell } from "@/components/mortgage/HouseShell";
import { formatMoney } from "@/lib/format/money";
import { houseValue, loadHouseCore } from "./house-page-data";

async function Content(){
  const {homes,deals,valuations}=await loadHouseCore(); const home=homes.find(h=>h.ownership_status==="current_home")??homes[0]; const deal=deals.find(d=>d.home_id===home?.id)??deals[0]; const value=houseValue(home,valuations), balance=Number(deal?.balance||0), equity=Math.max(0,value-balance); const attached=valuations.filter(v=>v.home_id===home?.id);
  return <HouseShell homes={homes} deals={deals} valuations={valuations}><div className="space-y-5"><div className="flex items-start justify-between gap-3"><div><p className="text-xs font-bold uppercase tracking-[0.16em] text-violet-600">Property</p><h1 className="mt-1 text-4xl font-bold text-slate-950">Your property</h1><p className="mt-2 text-sm font-semibold text-slate-500">Detailed information about your home.</p></div><Link href="/mortgage/advanced?intent=edit_home" className="rounded-xl border border-violet-200 px-4 py-2.5 text-xs font-bold text-violet-700">Edit property</Link></div>
  <section className="grid grid-cols-2 gap-2 sm:gap-3 xl:grid-cols-4">{[["Home value",formatMoney(value)],["Purchase price",formatMoney(Number(home?.purchase_price||0))],["Equity",formatMoney(equity)],["Valuation sources",String(attached.length)]].map(([l,m])=><div key={l} className="rounded-2xl border border-slate-200 bg-white p-4 shadow-sm"><p className="text-[10px] font-bold uppercase text-slate-400">{l}</p><p className="mt-2 text-2xl font-bold text-slate-950">{m}</p></div>)}</section>
  <section className="grid gap-4 xl:grid-cols-[.85fr_1.15fr]"><div className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><h2 className="text-lg font-bold">Property details</h2><dl className="mt-4 space-y-3 text-sm">{[["Address",home?.full_address||home?.address_line||"Not set"],["Postcode",home?.postcode||"Not set"],["Property type",home?.property_type||"Not set"],["Purchase date",home?.purchase_date||"Not set"],["UPRN",home?.uprn||"Not set"]].map(([l,v])=><div key={l} className="flex justify-between gap-4 border-b border-slate-100 pb-3"><dt className="font-semibold text-slate-500">{l}</dt><dd className="text-right font-bold text-slate-950">{v}</dd></div>)}</dl><Link href="/mortgage/advanced?intent=edit_home" className="mt-4 inline-block rounded-xl border border-violet-200 px-4 py-2.5 text-xs font-bold text-violet-700">Edit full property record</Link></div><div className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><h2 className="text-lg font-bold">Property value</h2><div className="mt-4 grid min-h-[240px] place-items-center rounded-xl bg-gradient-to-br from-violet-50 to-sky-50"><div className="text-center"><p className="text-4xl font-bold">{formatMoney(value)}</p><p className="mt-2 text-xs font-semibold text-slate-500">Current tracked value · {attached.length} source{attached.length===1?"":"s"}</p></div></div></div></section>
  <section className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><div className="flex justify-between gap-3"><h2 className="text-lg font-bold">Valuation sources</h2><Link href="/mortgage/advanced?intent=add_valuation" className="text-xs font-bold text-violet-700">+ Add valuation</Link></div><div className="mt-4 overflow-x-auto"><table className="w-full min-w-[680px] text-left text-xs"><thead className="text-slate-400"><tr><th className="py-2">Date</th><th>Source</th><th>Value</th><th>Range</th><th>Confidence</th></tr></thead><tbody className="divide-y divide-slate-100">{attached.map(v=><tr key={v.id}><td className="py-3">{v.valuation_date||"—"}</td><td className="font-bold">{v.source_name}</td><td className="font-bold">{formatMoney(Number(v.valuation_mid??v.valuation_amount??0))}</td><td>{v.valuation_low||v.valuation_high?`${formatMoney(Number(v.valuation_low||0))} – ${formatMoney(Number(v.valuation_high||0))}`:"—"}</td><td className="capitalize">{v.confidence||"medium"}</td></tr>)}</tbody></table></div></section></div></HouseShell>;
}
export default function HousePropertyPage(){return <><Nav/><Content/></>}
